apiVersion: v1
data:
  client-secret: ZzE3cE9mc3haVENNSXNRNkY3M3ZIMktod3I5ZzYwSUpFREJXZUd1cDBtdlp0elhN
kind: Secret
metadata:
  name: podinfo-keycloak-client-secret
  namespace: keycloak
type: Opaque
