apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-database-secret
    namespace: nextcloud
stringData:
    username: ENC[AES256_GCM,data:VFauk1/fCQtL,iv:D/lT7l7uBe7aSAUaM247IKlwASG+dNIBaB465Z+QIic=,tag:MGHSm/bZ07Qw3OeQRUx4bQ==,type:str]
    password: ENC[AES256_GCM,data:BbGaDhRiiW08,iv:Q09Yja0w2ooOT2ix8r89RpbRTKekv9Nz2sA+N8KjC2A=,tag:UrF2DH5eqhuu/yRi7U8F2A==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U3ZNVGZ0dlBMZlRnRk5s
            TWo3c0FYSy92QmhZYWh0eWhBSGkyZkZFc21VCkgraXpzeU80c2JmQWZFdHV1eFlK
            eXVBRUplbkRaa2Voc3pzVmVNUysrencKLS0tIFgxSWYxZVFKY3Z1YlBUTkpYTXp3
            ODU2STJHeHN4SHZ5QlhpNnNXR0EvaFEKEuCNcjupkzc1M52m42U/rdyriSXBkmoM
            6/rJ3/7m6eLgT9RCGywg72wLwOKjpjZcU3Z9zejO2bWvyftCNJeymQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:59:51Z"
    mac: ENC[AES256_GCM,data:XzNxtAwWCa2Nk1gwCJTjNJsUbNmqmFGX8YxD7Gh1OFKVkCr32o0uEYdnFFI3qZt7jx+OoROGS0d5qf6L3ZZ1F6YhrtxXt4pDQs+Oaa4FP8DCJDV4621kqTHh9RvWE92dpVo8EZ67N2e/DC9tGuioTrDZimBcGyzIq1uOTiwShAs=,iv:rQsIJKuROSGvtl71R/3PnIksTlBoTZJtd5aPCsVW9gU=,tag:fuR2C+z7hk9mA8vDd+UAOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
