{{- if and .Values.platformAuth.keycloak.enabled .Values.platformAuth.keycloak.groups }}
{{- $root := . }}
{{- range .Values.platformAuth.keycloak.groups }}
{{- if .enabled }}
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmGroup
metadata:
  name: {{ .name | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ include "common.names.namespace" $root }} 
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  {{- with $root.Values.platformAuth.keycloak.realm }}
  realmRef:
    name: {{ .name }}
    kind: "KeycloakRealm"
  {{- end }}
  name: {{ .groupName | quote }}
{{- end }}
{{- end }}
{{- end }}
