{{- if .Values.platformAuth.keycloak.enabled }}
{{- $kind := .Values.platformAuth.keycloak.instance.scope }}

{{- if not (has $kind (list "namespace" "cluster")) }}
{{- fail "platformAuth.keycloak.instance.scope must be either 'namespace' or 'cluster'" }}
{{- end }}

{{- if eq $kind "cluster" }}
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm  
metadata:
  name: {{ .Values.platformAuth.keycloak.realm.name | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  realmName: {{ .Values.platformAuth.keycloak.realm.name | quote }}
  clusterKeycloakRef: keycloak-cluster-endpoint
{{- end }}
{{- end }}
