{{- if .Values.platformAuth.keycloak.enabled }}
{{- $kind := .Values.platformAuth.keycloak.instance.scope }}

{{- if not (has $kind (list "namespace" "cluster")) }}
{{- fail "platformAuth.keycloak.instance.scope must be either 'namespace' or 'cluster'" }}
{{- end }}

{{- if eq $kind "cluster" }}
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  name: keycloak-cluster-endpoint
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  url: {{ .Values.platformAuth.keycloak.instance.url | quote }}
  secret: {{  .Values.platformAuth.keycloak.instance.secret | quote }}
{{- end }}
{{- end }}
