{{- if .Values.platformAuth.keycloak.enabled }}
{{- $scope := .Values.platformAuth.keycloak.realm.scope | default "namespace" }}

{{- if not (has $scope (list "namespace" "cluster")) }}
{{- fail "platformAuth.keycloak.realm.scope must be either 'namespace' or 'cluster'" }}
{{- end }}


{{- $kind := "KeycloakRealm" }}
{{- $keycloakKind := "Keycloak" }}

{{- if eq $scope "cluster" }}
{{- $kind = "ClusterKeycloakRealm" }}
{{- $keycloakKind = "ClusterKeycloak" }}
{{- end }}

apiVersion: v1.edp.epam.com/v1
kind: {{ $kind }}
metadata:
  name: {{ .Values.platformAuth.keycloak.realm.name | trunc 63 | trimSuffix "-" | quote }}
  {{- if eq $scope "namespace" }}
  namespace: {{ include "common.names.namespace" . }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  realmName: {{ .Values.platformAuth.keycloak.realm.name | quote }}
  keycloakRef:
    name: keycloak-endpoint
    kind: {{ $keycloakKind }}
{{- end }}
