{{- if .Values.platformAuth.keycloak.enabled }}
{{- $scope := .Values.platformAuth.keycloak.realm.scope | default "namespace" }}
apiVersion: v1.edp.epam.com/v1alpha1
kind: {{ ternary "ClusterKeycloak" "Keycloak" (eq $scope "cluster") }}
metadata:
  name: keycloak-endpoint
  {{- if eq $scope "namespace" }}
  namespace: {{ include "common.names.namespace" . }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  url: {{ .Values.platformAuth.keycloak.endpoint.url | quote }}
  secret: {{  .Values.platformAuth.keycloak.endpoint.secret | quote }}
{{- end }}
