apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-endpoint
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  url: {{ .Values.platformAuth.keycloak.endpoint.url | quote }}
  secret: {{  .Values.platformAuth.keycloak.endpoint.secret | quote }}
