{{- if and .Values.platformAuth.keycloak.enabled .Values.platformAuth.keycloak.users }}
{{- $root := . }}
{{- range $user := .Values.platformAuth.keycloak.users }}

{{- $userDetails := mergeOverwrite (deepCopy $root.Values.platformAuth.keycloak.userDefaults) $user }}
{{- if $userDetails.enabled }}

{{- $passwordSecret := $userDetails.passwordSecret | default dict }}
{{- $userResourceName := $userDetails.username | replace "." "-" | trunc 56 | trimSuffix "-" }}

{{- if not (has $passwordSecret.mode (list "existing" "create" "none")) }}
{{- fail (printf "Invalid passwordSecret.mode for user %s. Allowed values: existing, create, none" $userDetails.username) }}
{{- end }}

{{- if and (eq $passwordSecret.mode "existing") (not $passwordSecret.name) }}
{{- fail (printf "User %s has passwordSecret.mode=existing but passwordSecret.name is empty" $userDetails.username) }}
{{- end }}

{{- if and (eq $passwordSecret.mode "create") (not $passwordSecret.value) }}
{{- fail (printf "User %s has passwordSecret.mode=create but passwordSecret.value is empty" $userDetails.username) }}
{{- end }}

{{- if eq $passwordSecret.mode "create" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" $userResourceName) $userDetails.passwordSecret.name | quote }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
type: Opaque
stringData:
  {{ $passwordSecret.key }}: {{ $passwordSecret.value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
