{{- if and .Values.platformAuth.keycloak.enabled .Values.platformAuth.keycloak.users }}
{{- $root := . -}}
{{- range $u := .Values.platformAuth.keycloak.users }}
{{- $user := mergeOverwrite (deepCopy $root.Values.platformAuth.keycloak.userDefaults) $u }}
{{- $userResourceName := $user.username | replace "." "-" | trunc 63 | trimSuffix "-" }}
{{- $requiredUserActions := $user.requiredUserActions | default list }}
{{- $passwordSecretNameProvided := and $user.passwordSecret (hasKey $user.passwordSecret "name") $user.passwordSecret.name }}
{{- if not $passwordSecretNameProvided }}
{{- $requiredUserActions = append $requiredUserActions "UPDATE_PASSWORD" | uniq
}}
{{- end }}
{{- if $user.enabled }}
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: {{ $userResourceName | quote }}
  namespace: {{ include "common.names.namespace" $root }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  realmRef:
    name: {{ $root.Values.platformAuth.keycloak.realm.name | quote }}
    kind: "KeycloakRealm"

  username: {{ $user.username | quote }}

  {{- with $user.firstName }}
  firstName: {{ . | quote }}
  {{- end }}

  {{- with $user.lastName }}
  lastName: {{ . | quote }}
  {{- end }}

  {{- with $user.email }}
  email: {{ . | quote }}
  {{- end }}

  {{- if hasKey $user "emailVerified" }}
  emailVerified: {{ $user.emailVerified }}
  {{- end }}

  {{- if hasKey $user "enabled" }}
  enabled: {{ $user.enabled }}
  {{- end }}

  {{- with $user.reconciliationStrategy }}
  reconciliationStrategy: {{ . | quote }}
  {{- end }}

  {{- if hasKey $user "keepResource" }}
  keepResource: {{ $user.keepResource }}
  {{- end }}

  {{- if hasKey $user "keepResource" }}
  passwordSecret:
    name: {{ default (printf "%s-secret" $userResourceName) $user.passwordSecret.name | quote }}
    key: {{ default "password" $user.passwordSecret.key | quote }}

  {{- with $requiredUserActions }}
  requiredUserActions:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $user.roles }}
  roles:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $user.groups }}
  groups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
