{{- if and .Values.certificate.enabled .Values.certificate.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ default (printf "%s-issuer" (include "common.names.fullname" .)) .Values.certificate.issuer.name }}
  namespace: {{ default (include "common.names.namespace" .) .Values.certificate.issuer.namespace }}
spec:
  {{- with .Values.certificate.issuer.acme }}
  acme:
    email: {{ required "certificate.issuer.acme.email is required" .email | quote }}
    server: {{ required "certificate.issuer.acme.server is required" .server | quote }}
    privateKeySecretRef:
      name: {{ required "certificate.issuer.acme.privateKeySecretName is required" .privateKeySecretName | quote }}
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              {{- range .gatewayHTTPRoute.parentRefs }}
              - group: {{ default "gateway.networking.k8s.io" .group }}
                kind: {{ default "Gateway" .kind }}
                name: {{ required "certificate.issuer.acme.gatewayHTTPRoute.parentRefs[].name is required" .name }}
                namespace: {{ required "certificate.issuer.acme.gatewayHTTPRoute.parentRefs[].namespace is required" .namespace }}
              {{- end }}
  {{- end }}
{{- end }}
