# --
# 
# 
# --
applications:
   
  # 
  # Envoy-Gateway 
  #

    - name: envoy-gateway 
      chartName: envoy-gateway
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -1

    - name: envoy-gateway-crds
      chartName: envoy-gateway-crds
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
      manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -1
