# ===============================
# 
# 
# ===============================
applications:
   
  # ------------------
  # Envoy-Gateway-CRD's (gateway-api)
  # ------------------

    - name: envoy-gateway-crds
      chartName: envoy-gateway-crds
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
      #manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -10

  # ------------------
  # Envoy-Gateway 
  # ------------------
  
    - name: envoy-gateway 
      chartName: envoy-gateway
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -5

  # ------------------
  # Cert-Manager 
  # ------------------

    - name: cert-manager
      chartName: jetstack/cert-manager
      #chartPath: 
      targetRevision: 1.16.3
      repoURL: https://charts.jetstack.io
      manifests: true
      chartValues: true
      namespace: cert-manager 
      priority: -5

  # ------------------
  # Podinfo
  # ------------------

    - name: podinfo
      chartName: podinfo
      #chartPath: 
      targetRevision: 6.9.1
      repoURL: https://stefanprodan.github.io/podinfo
      manifests: true
      chartValues: true
      namespace: podinfo 
      priority: 0
