# --
# 
# 
# --
applications:
   
  # 
  # Envoy-Gateway 
  #

    - name: envoy-gateway 
      chartName: envoy-gateway
      chartPath: ./charts/gateway-helm/
      targetRevision: v1.7.2
      repoURL: https://github.com/envoyproxy/gateway
      manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -1
