# ===============================
# Public key: age1v2jdckfv9x77zdv7pynrnw9rxlrzgvlymft0qv879dgf2rtwy3lqg4mxp6
# 
# ===============================
applications:
   
  # ------------------
  # SOPS 
  # ------------------

    - name: sealed-secrets
      chartName: sealed-secrets
      #chartPath: 
      targetRevision: 2.16.1 
      repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
      #manifests: true
      chartValues: true
      namespace: sealed-secrets 
      priority: -15

  # ------------------
  # Envoy-Gateway-CRD's (gateway-api)
  # ------------------

    - name: envoy-gateway-crds
      chartName: envoy-gateway-crds
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
      #manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -10

  # ------------------
  # Envoy-Gateway 
  # ------------------
  
    - name: envoy-gateway 
      chartName: envoy-gateway
      #chartPath: 
      targetRevision: v1.7.1
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      manifests: true
      chartValues: true
      namespace: envoy-gateway-system
      priority: -5

  # ------------------
  # Cert-Manager 
  # ------------------

    - name: cert-manager
      chartName: cert-manager
      #chartPath: 
      targetRevision: 1.20.2
      repoURL: https://charts.jetstack.io
      #manifests: true
      chartValues: true
      namespace: cert-manager 
      priority: -5

  # ------------------
  # Podinfo
  # ------------------

    - name: podinfo
      chartName: podinfo
      #chartPath: 
      targetRevision: 6.9.1
      repoURL: https://stefanprodan.github.io/podinfo
      manifests: true
      chartValues: true
      namespace: podinfo 
      priority: 0
