apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccess
metadata:
  name: sample 
  namespace: seaweedfs 
spec:
  bucketAccessClassName: sample
  bucketClaimName: app-bucket
  credentialsSecretName: sample-bc-secret
  protocol: s3
