services:
  master:
    image: chrislusf/seaweedfs:latest
    command: "master -ip=master"
    volumes:
      - /srv/seaweedfs/master:/data
    ports:
      - "9333:9333"

  volume:
    image: chrislusf/seaweedfs:latest
    command: "volume -mserver=master:9333 -ip=volume -dir=/data -max=0"
    volumes:
      - /srv/seaweedfs/volume:/data
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs:latest
    command: "filer -master=master:9333"
    volumes:
      - /srv/seaweedfs/filer:/data
    ports:
      - "8888:8888"
    depends_on:
      - master
      - volume

  s3:
    image: chrislusf/seaweedfs:latest
    command: "s3 -filer=filer:8888 -port=8333"
    ports:
      - "8333:8333"
    depends_on:
      - filer
