#apiVersion: v1
#kind: Secret
#metadata:
#  name: rclone-config
#type: Opaque
#stringData:
#  rclone.conf: |
#    [primary-seaweedfs]
#    type = s3
#    provider = Other
#    endpoint = http://PRIMARY_CLUSTER_S3_ENDPOINT:8333
#    access_key_id = PRIMARY_ACCESS_KEY
#    secret_access_key = PRIMARY_SECRET_KEY
#    acl = private
#
#    [backup-minio]
#    type = s3
#    provider = Minio
#    endpoint = http://minio.backup.svc.cluster.local:9000
#    access_key_id = BACKUP_ACCESS_KEY
#    secret_access_key = BACKUP_SECRET_KEY
#    acl = private
---
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-backup-secrets
  namespace: seaweedfs
stringData:
    SRC_ACCESS_KEY: ""
    SRC_SECRET_KEY: ""
    DST_ACCESS_KEY: ""
    DST_SECRET_KEY: ""
