# ===========================================================
# Purpose:  
# Notes:
# - 1) Use Bcrypt to generate password
#
#   stringData:
#     admin.password: htpasswd -bnBC 10 "" 'CHANGE-ME' | tr -d ':\n'
#     admin.passwordMtime: date -u +%FT%TZ
#
# - 2) Encrypt this secret via SOPS
#   - sops encrypt -i secret.sops.yaml
# ===========================================================
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:/xaWx0YdyuuhnWUgnYJg0BsiwjGCCL0GsfYTJ+pTaM9qQTYWtIIFZ3OHUDsvFKuDDxP55siHxuaUZ2re,iv:sRxFGlzNqlaQbBca8P3Aqtf6K46jh4rxqt8IQm8ec3I=,tag:uhrJM+IbTZK2FIp2c2Eg6A==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:9i7PaIGHU98sfp2JskwKN/gSVUU=,iv:533kaXyh9XBWC/RvwkqO6HEbmgaNVMNBSe4Un/OV3Jk=,tag:cUUatnDv7Bak1TSZhfMfbg==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQmRmRXJSZ0YrSzlBM0JT
            ai95Qlp0dDlHbUlBZC9tYTF5OUdvMDhNY1E4CmtXNFRnNzN2QmxJbUtuWitoY0Jq
            dEdKeXRZZURXSzRMazFieUFOb3Z2UXcKLS0tIFlhSHc1aE90K0c4TFFPeWNtWmJa
            UXhTemRQUEh0SUNKQ21rYXA3UGhybkkKzfLI6idL+7E2OXSTz6ySkTIimq3JVEkY
            LKlgJIwsBKzm4PskU2uv5gIW8cNgBiuIGTOnJNocnXccd0NHyCv9Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:28:11Z"
    mac: ENC[AES256_GCM,data:6SuVd24EkYkFReIGbfCtTbGs+Flj90ybPmCRgDuGXfky3WKuXYaBShIdHPCr0kz96JkaNTgXM1Qfmd0xpqVCiGqeF+bba+13B22BClPsG2aDVl8Sc5go3q26Jc4ycKMjiHls1N6rzd6cm0Z3CY2BeTBBuJYiZ9HeJplwquqtq3Q=,iv:+mPVMwpa2txCJYmpP6T0OVfna17P6igxMUBVA8GV8lo=,tag:XX+RJVKttyJg5eX77JvqRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
