apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-entrypoint
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  entrypoint: |
    #!/usr/bin/env bash
    set -euo pipefail

    exec /usr/sbin/slapd \
      -h "ldap://:389 ldaps://:636 ldapi:///" \
      -u openldap \
      -g openldap \
      -d "${LDAP_LOG_LEVEL:-256}" \
      -F /etc/ldap/slapd.d
