{{- if not .Values.openldap.configuration.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secrets
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ .Values.openldap.configuration.adminPassword | quote }}
  LDAP_CONFIG_PASSWORD: {{ .Values.openldap.configuration.configPassword | quote }}
{{- end }}
