creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age15auqe06w4jw4awxgcmsxa6fxg9nve8jnxdemxeuq0y2pepmx3uus7umr0g

# ----------------- 
# Encrypt Kubernetes Secret
# -----------------
# - sops encrypt -i secret.sops.yaml

# ----------------- 
# Decrypt Kubernetes Secret
# -----------------
# - export SOPS_AGE_KEY_FILE=/path/to/key.age
#   sops encrypt -i secret.sops.yaml
