creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z

# ----------------- 
# Encrypt Kubernetes Secret
# -----------------
# - sops encrypt -i secret.sops.yaml

# ----------------- 
# Decrypt Kubernetes Secret
# -----------------
# - export SOPS_AGE_KEY_FILE=/path/to/key.age
#   sops encrypt -i secret.sops.yaml
