# ===============================================================
# Author:
# - 
#
# Purpose:
# - pgadmin helm chart values.yaml file
#
# ===============================================================

env:
  email: admin@anykey.pl
  password: admin

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: storage-local-retain
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"     

# ===============================================================
# : Default configuration fro platfrom wrappers
# ===============================================================

platformDefaults:
  appName:              &appName              pgadmin4
  namespace:            &namespace            pgadmin4
  domain:               &domain               pgadmin4.anykey.pl
  gatewayNamespace:     &gatewayNamespace     envoy-gateway-system
  certificateName:      &certificateName      pgadmin4-tls-certificate
  gatewayName:          &gatewayName          gateway-pgadmin4
  issuerName:           &issuerName           issuer-pgadmin4
  serviceName:          &serviceName          pgadmin4
  issuerEmail:          &issuerEmail          pgadmin4@anykey.pl
  httpRouteName:        &httpRouteName        pgadmin4-host
  httpRouteServicePort: &httpRouteServicePort 80 

# ===============================================================
#    ___             ___  __     __  ___             
#   / _ | ___  ___  / _ \/ /__ _/ /_/ _/__  ______ _ 
#  / __ |/ _ \/ _ \/ ___/ / _ `/ __/ _/ _ \/ __/  ' \
# /_/ |_/ .__/ .__/_/  /_/\_,_/\__/_/ \___/_/ /_/_/_/
#      /_/  /_/                                      
#
# : AppPlatform (wrapper chart)
# ===============================================================

appPlatform:

  # ===============================================
  # @section gatewayApi parameters
  # ===============================================
  
  gatewayApi:
    # @param appPlatform.gatewayApi.enabled Enable Gateway API resources.
    enabled: true

    # @param appPlatform.gatewayApi.gateway.enabled Enable Gateway resource generation.
    # @param appPlatform.gatewayApi.gateway.name Gateway resource name.
    # @param appPlatform.gatewayApi.gateway.namespace Namespace where the Gateway will be created.
    # @param appPlatform.gatewayApi.gateway.labels Labels to add to the Gateway.
    # @param appPlatform.gatewayApi.gateway.annotations Annotations to add to the Gateway.
    # @param appPlatform.gatewayApi.gateway.gatewayClassName GatewayClass name used by the Gateway.
    # @param appPlatform.gatewayApi.gateway.listeners List of Gateway listeners. 
    gateway:
      enabled: true
      name: *gatewayName
      namespace: *gatewayNamespace
      annotations:
        external-dns.alpha.kubernetes.io/target: anykey.pl
      gatewayClassName: envoy

      # @param appPlatform.gatewayApi.gateway.listeners[0].name Listener name.
      # @param appPlatform.gatewayApi.gateway.listeners[0].protocol Listener protocol.
      # @param appPlatform.gatewayApi.gateway.listeners[0].port Listener port.
      # @param appPlatform.gatewayApi.gateway.listeners[0].hostname Hostname accepted by the listener.
      # @param appPlatform.gatewayApi.gateway.listeners[0].allowedRoutes Allowed routes configuration.
      listeners:
        - name: listener-http
          protocol: HTTP
          port: 80
          hostname: *domain
          allowedRoutes:
            namespaces:
              from: All

        - name: listener-https
          protocol: HTTPS
          port: 443
          hostname: *domain
          tls:
            mode: Terminate
            certificateRefs:
              - name: *certificateName
          allowedRoutes:
            namespaces:
              from: Selector
              selector:
                matchLabels:
                  kubernetes.io/metadata.name: *namespace
 
    # @param appPlatform.gatewayApi.httpRoute.enabled Enable HTTPRoute resource generation.
    # @param appPlatform.gatewayApi.httpRoute.name HTTPRoute resource name.
    # @param appPlatform.gatewayApi.httpRoute.namespace Namespace where the HTTPRoute will be created.
    # @param appPlatform.gatewayApi.httpRoute.labels Labels to add to the HTTPRoute.
    # @param appPlatform.gatewayApi.httpRoute.annotations Annotations to add to the HTTPRoute.
    # @param appPlatform.gatewayApi.httpRoute.parentRefs Parent Gateway references.
    # @param appPlatform.gatewayApi.httpRoute.hostnames Hostnames matched by the HTTPRoute.
    # @param appPlatform.gatewayApi.httpRoute.rules HTTPRoute routing rules.
    httpRoutes:

      - enabled: true
        name: *httpRouteName 
        namespace: *namespace
        parentRefs:
          - name: *gatewayName
            namespace: *gatewayNamespace
            sectionName: listener-https
        hostnames:
          - *domain
        rules:
          - backendRefs:
              - kind: Service
                name: *serviceName
                namespace: *namespace
                port: *httpRouteServicePort 

      - enabled: true
        name: http-redirect
        namespace: *namespace
        parentRefs:
          - name: *gatewayName
            namespace: *gatewayNamespace
            sectionName: listener-http
        hostnames:
          - *domain
        rules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  scheme: https
                  statusCode: 301
                  port: 443
  
  # ===============================================
  # @section Certificate parameters
  # ===============================================
  
  # @param appPlatform.certificate.enabled Enable Certificate resource generation.
  # @param appPlatform.certificate.name Certificate resource name.
  # @param appPlatform.certificate.namespace Namespace where the Certificate will be created.
  # @param appPlatform.certificate.existingIssuer Name of an existing Issuer or ClusterIssuer.
  # @param appPlatform.certificate.existingIssuerKind Kind of the existing issuer. Usually Issuer or ClusterIssuer.
  # @param appPlatform.certificate.keySize Private key size.
  # @param appPlatform.certificate.keyAlgorithm Private key algorithm.
  # @param appPlatform.certificate.duration Certificate validity duration.
  # @param appPlatform.certificate.renewBefore How long before expiry cert-manager should renew the certificate.
  # @param appPlatform.certificate.secretName Secret name where the TLS certificate will be stored.
  # @param appPlatform.certificate.dnsNames DNS names covered by the certificate. 
  certificate:
    enabled: true
    name: *certificateName
    namespace: *gatewayNamespace
    existingIssuer: *issuerName
    secretName: *certificateName
    dnsNames:
      - *domain

    # -----------------------------------------------
    # @subsection Issuer parameters
    # -----------------------------------------------
    #
    # @param appPlatform.certificate.issuer.enabled Enable Issuer resource generation.
    # @param appPlatform.certificate.issuer.name Issuer resource name.
    # @param appPlatform.certificate.issuer.namespace Namespace where the Issuer will be created.
    # @param appPlatform.certificate.issuer.kind Issuer kind. Usually Issuer or ClusterIssuer.
    # @param appPlatform.certificate.issuer.acme.email ACME registration email.
    # @param appPlatform.certificate.issuer.acme.server ACME server URL.
    # @param appPlatform.certificate.issuer.acme.privateKeySecretName Secret name used to store the ACME account private key.
    # @param appPlatform.certificate.issuer.acme.gatewayHTTPRoute.parentRefs Gateway parent references used for HTTP-01 challenges. 
    issuer:
      enabled: true
      name: *issuerName
      namespace: *gatewayNamespace
      acme:
        email: *issuerEmail
        gatewayHTTPRoute:
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: *gatewayName
              namespace: *gatewayNamespace

# ===============================================================
#    ___             ____                 _ __      
#   / _ | ___  ___  / __/__ ______ ______(_) /___ __
#  / __ |/ _ \/ _ \_\ \/ -_) __/ // / __/ / __/ // /
# /_/ |_/ .__/ .__/___/\__/\__/\_,_/_/ /_/\__/\_, / 
#      /_/  /_/                              /___/
#
# : AppSecurity (wrapper chart)
# ===============================================================

appSecurity:
  enabled: true

  # ===============================================
  # @section NetworkPolicy parameters
  # ===============================================

  # @param appSecurity.networkPolicies List of NetworkPolicy resources to generate.
  networkPolicies:
  
  # : Allow consuming Kubernetes DNS 
  - enabled: true
    name: allow-dns-egress
    namespace: *namespace
    podSelector:
      matchLabels:
        app.kubernetes.io/name: *appName
    policyTypes:
      - Egress 
    egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system 
        ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    ingress: []

  # : Allow ingress traffic to from envoy-gatawy-system
  - enabled: true
    name: allow-from-gateway
    namespace: *namespace 
    labels: {}
    annotations: {}
    podSelector:
      matchLabels:
        app.kubernetes.io/name: *appName
    policyTypes:
      - Ingress
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
    egress: []

  # : Block all ingress and egress in namespace
  - enabled: true
    name: deny-all-ingress-egress
    namespace: *namespace
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
    ingress: []

  # : Allow egress traffic to sql instances 
  - enabled: true
    name: allow-pgadmin-to-sql
    namespace: *namespace 
    labels: {}
    annotations: {}
    podSelector:
      matchLabels:
        app.kubernetes.io/name: *appName
    policyTypes:
      - Egress 
    egress:
      - ports:
        - protocol: TCP 
          port: 5432
    ingress: []
