# ===========================================================
# Purpose:  
# Notes:
# - 1) Use Bcrypt to generate password
#
#   stringData:
#     admin.password: htpasswd -bnBC 10 "" 'CHANGE-ME' | tr -d ':\n'
#     admin.passwordMtime: date -u +%FT%TZ
#
# - 2) Encrypt this secret via SOPS
#   - sops encrypt -i secret.sops.yaml
# ===========================================================
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:rKxbfvUQUzH4JeEPjBvmx3uH4oBHlG+LMoFSyW2J6EMcDPbUhrlUGj5NcZG2opvWH1TKe7qbiS7NpT0Q,iv:eX7o1sDZlV2enpFRekNZ/5C2dD2qbJ6jB8dIKpguFew=,tag:kJwcHsuA4fJQeF/I6GZ0tg==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:Qo8f+FfvDWVsavS/NWr/OmdWrds=,iv:OVexSl/X4EtTKVzzV9dv/J8cEE5Abxmj0RbwQLZ2bks=,tag:VMAmHWUC+TmNhsKReCz+ag==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbWd2R3lvSjNOUS9HRFhi
            N1VpWGl3QW5yV3N2RzZmSWRhdDBHa3BkOUNjCjd5aVJYM3BEb2phcWxDL2xRWDJF
            VkkxN0JEK29DbTFwa3B1MDVIWWQ5aU0KLS0tIDlwTStVbnRHb3pvV3FyN0REZDgr
            Y041cEpYc0JrSUVUODd5M2tiYXhoU1EK4wOpLpt1Cb55XCsPLk0pzYTeyH8pifik
            SrRHPefBw60CTtP3UE1kdOxse5ci+GAf7eUU1z6A3JrWPKV2G14WTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T11:14:26Z"
    mac: ENC[AES256_GCM,data:FiptrLr4qRjMknZIo4YBRfgiy/j+sHw1fV2Yje91160cYENOyJozgj6LkIjuctWg0ed0kCqdLbDRZ27AKELGIP9F5jC7lxZZsPML6TWPcxqYOyDtdstAkNNwrcNPWacJaBxaEpm//ZXX9vz7tJ/sVaP/xUzJdaajitAu5wuewzk=,iv:qc0Do+HZbleSkQOk8YLzEjhSJD8Xf88fBmZsoSPlEns=,tag:JHAayJ8uXjHzIHd+JeVa3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
