# ===============================
# 
# ===============================
applications:

  # ------------------
  # CloudNative-PG
  # ------------------

    - name: cloudnative-pg 
      enabled: true 

      namespace: 
        name: postgresql-operator
        autocreate: "true"

      syncPolicy:
        automated: false
        syncOptions:
          - ServerSideApply=true

  # ------------------
  # Container Object Storage Interface (COSI)
  # ------------------

    - name: cosi 
      enabled: true 

      namespace: 
        name: cosi 
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # Local Path Provisioner 
  # ------------------

    - name: local-path-provisioner 
      enabled: true 

      namespace: 
        name: kube-system 
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # SeaWeedFS 
  # ------------------

    - name: seaweedfs 
      enabled: true 

      namespace: 
        name: seaweedfs 
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # SeaWeedFS-Operator
  # ------------------

    - name: seaweedfs-operator
      enabled: true 

      namespace: 
        name: seaweedfs 
        autocreate: "true"

      syncPolicy:
        automated: true
