apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:xXV0pMoqagL5,iv:om5s/rd5v2PbCE2ID6/e+pspOcpjhHJh43L82SiC0Q4=,tag:BI96ncZP5EXHJS8c3wJcmw==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:JaAhvr7Y+lma,iv:EiSNQiKq212o2qG96pkYjWMk5lOCJmxwfkgt/bflEkc=,tag:m1CPV6tiQRJf9zS36yqxTg==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbDVMY2VjNWZvTGdTVkVR
            aXkrYklPMkxBOHFKblN2MmdDY1pLN1RQM1EwCldEOEgxV2lrOUFzSXpVQlljeWNj
            L05HaDBkei9YOUxwdGpvaTdFZ1U0R0EKLS0tIE5qcU4xQ0d3WGdVN2tQc0t3T1J4
            TUVlVDB3WFBqaWxZUnZlNCtqTEVLT00K/U7+A7l6mcK4TFmzz/pKOO/kX3qAhNDY
            psHBpQq7+wrIDLOw54hnvok9BahFj06XulRSDjLMijL5nHCtPat3IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:22:21Z"
    mac: ENC[AES256_GCM,data:z7Z6GlOhtv1B/2+bKH3WbcxEWp1U9JdyBC3rUoJeV8NLzdpDH1PVtXn5sJhYTDHelU1mTn06eFim+YHZ5hcQa0aIKNA8Is4CeBuSUO9tbIwcTIMqDYYilguWH+JrFWVMdDaPb5PubuF2pChjG590nnJevsBQL8URb/4PO0yLiZA=,iv:ZqVISOTGsZvLavrdHGZTu7RIpxYCz6w0YPqsbNU1WJg=,tag:OwHPrxn9XufdZ7akIFklIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
