# ===============================
# 
# ===============================
applications:
   
  # ------------------
  # Envoy-Gateway-CRD's (gateway-api)
  # ------------------

    - name: envoy-gateway-crds
      namespace: envoy-gateway-system

      enabled: true
      priority: -10

      syncPolicy:
        automated: true
        syncOptions:
          - ServerSideApply=true

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
          targetRevision: v1.7.1
          chart: envoy-gateway-crds
          valueFiles: 
            - $values/platform-products/platform-core/applications/envoy-gateway-crds/helm/values.yml
        
        - type: manifest
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-core/applications/envoy-gateway-crds/manifests
          recurse: true

        - type: kustomize
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-core/applications/envoy-gateway-crds/kustomize

  # ------------------
  # Envoy-Gateway 
  # ------------------
  
    - name: envoy-gateway
      namespace: envoy-gateway-system

      enabled: true
      priority: -5

      syncPolicy:
        automated: true
        syncOptions:
          - ServerSideApply=true

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: oci://docker.io/envoyproxy/gateway-helm
          targetRevision: v1.7.1
          chart: envoy-gateway-crds
          valueFiles: 
            - $values/platform-products/platform-core/applications/envoy-gateway/helm/values.yml
        
        - type: manifest
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-core/applications/envoy-gateway/manifests
          recurse: true

  # ------------------
  # Cert-Manager 
  # ------------------
  
    - name: cert-manager 
      namespace: cert-manager 

      enabled: true
      priority: -5

      syncPolicy:
        automated: true

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://charts.jetstack.io
          targetRevision: 1.20.2 
          chart: cert-manager 
          valueFiles: 
            - $values/platform-products/platform-core/applications/cert-manager/helm/values.yml

  # ------------------
  # Exteranl-DNS 
  # ------------------
  
    - name: external-dns
      namespace: external-dns

      enabled: true
      priority: 0

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://kubernetes-sigs.github.io/external-dns/
          targetRevision: 1.20.0
          chart: cert-manager 
          valueFiles: 
            - $values/platform-products/platform-core/applications/external-dns/helm/values.yml

        - type: kustomize 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-core/applications/external-dns/kustomize
