name: dev
products:
  - platform-core
  - platform-core-extras

  - platform-storage
  - platform-storage-extras

  - platform-security
  - platform-security-extras

  - workload-storage
  - workload-tests

#  - platform-observability
#  - platform-security
#  - gpu
#  - infrastructure
