name: dev
products:
  - platform-core
  - platform-storage
  - platform-security
  - platform-storage-extras
  - workload-tests

#  - platform-extras
#  - platform-observability
#  - platform-security
#  - gpu
#  - infrastructure
