# ===========================================================
# Purpose:  
# Notes:
# ===========================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-certificate
  namespace: envoy-gateway-system
spec:
  secretName: argocd-tls-certificate
  issuerRef: 
    name: issuer-argocd
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - argocd.anykey.pl
---
