# ===============================
# 
# ===============================
applications:

  # ------------------
  # Nextcloud 
  # ------------------

    - name: nextcloud
      enabled: true

      namespace:
        name: nextcloud
        autocreate: "true"
        labels:
          shared-credentials: "true"

      syncPolicy:
        automated: false
