# ===============================
# 
# ===============================
applications:

  # ------------------
  # Nextcloud 
  # ------------------

    - name: nextcloud
      enabled: false
      namespace:
        autocreate: "true"
        labels:
          shared-s3-creds: "true"

