# ===============================
# 
# ===============================
applications:

  # ------------------
  # Podinfo
  # ------------------

    - name: nextcloud 
      namespace: nextcloud 

      enabled: true
      priority: 0

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://nextcloud.github.io/helm/
          targetRevision: 9.0.6
          chart: nextcloud
          valueFiles: 
            - $values/platform-products/workload-storage/applications/nextcloud/helm/values.yml

        - type: kustomize 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-storage/applications/nextcloud/kustomize

        - type: manifests
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-storage/applications/nextcloud/manifests
