apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secret-generator 
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./nextcloud-admin-secret.sops.yml
  - ./nextcloud-database-secret.sops.yml
  - ./nextcloud-keycloak-client-secret.sops.yml
  - ./nextcloud-integrations-secret.sops.yml
  - ./seaweedfs-s3-secret.sops.yml
