apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-database-secret
    namespace: nextcloud
stringData:
    username: ENC[AES256_GCM,data:dPK8XzljrLkl,iv:1nnMA0PUTMYpB6HAeTAMqC5Z4JY56cnQ9ZNLn+C085g=,tag:lPwz/E1UD69T9/NY4YiPdg==,type:str]
    password: ENC[AES256_GCM,data:me5llgEvjU3W,iv:jHtqYsucO/82QMLPzV+Bd/5HazI/7GPdSUcp/Vixx7E=,tag:dFR8ZiekxQ8JkfvKJ4Co4w==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3dIa3pHV25vd0tMdDZS
            bG5UWFZXcDUxbHk2MEFBdktrOXhzdTg4NlM0CjB4TEFMMjc4YkxHbXhsZ0Y2Qi84
            bGY4VGtueDBwaDAzRlVjRDZGbVR2QmMKLS0tIGZsRTVCdnBZaWlLSDFtNzMxM1Rx
            U0hicEk5dFhiQ1A1cmRpUjZ6QUNCSm8KJM1dWQRjLOofM+rP4GP01dcb4hCh+I8u
            rG4qjPUMzfMZsY9fbm4CXHyAEb7MG9ZqQXTm29whEGOzsJJYXtm92w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T07:34:33Z"
    mac: ENC[AES256_GCM,data:uRqHoyO+qbqg/0JV8mGhrfGCGhZGXlVa8wHgU0g/oad/CohWqQ1890eNsqdnjL3s2iKV6+Kl81de4uDn3ZV+1HSZ/adnP9vxITQ7Dr+X8MWz8aGVNM7tplXCtX2lVF4pimWL5OcibRg7ofzUB7XLLIoM7C1fLLMqwNkP4RW3Z2E=,iv:IvF6XTjE/IY6cBBFHSDPHfUjdWC8BvzcTiEwLtYjq3Q=,tag:TtZAVF8WWrIXfUPjQMn35w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
