apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-secret
    namespace: nextcloud
stringData:
    username: ENC[AES256_GCM,data:c2oM/rSe1HkS,iv:KaLVjJq+V0Vz1CZJ2aNwIfA/IgNGmKZWUNv2o45VH6M=,tag:Yws76u8UF4HE6UFas4zhRw==,type:str]
    password: ENC[AES256_GCM,data:5fRUaN04d0ii,iv:blJxUTGDvWyGFYMwzDhRFfXqeNYNIsGNfvmP9SVDk28=,tag:Ef25/2Ojn55066clLjB01A==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVDRaeDg3OGtVYTJrdXpl
            K3VFN1QzeWdydHRXSjB2TzRTVTlLVmN4NzE4Cml0MFUzTlQ5Z0VjU3R1SGxkTkFv
            eDMwNWUxdHVRQ1htY1VZMlFwMTVoMjgKLS0tIFJRTHMyMXFNTXJ0b0IzaTc3MzZ4
            YUQ4VnRwdDFpYS9Pa1VmTFlMcGFrUjAK0LLDRcj+I37PY6pxJhQHPRSdxjEMA684
            k9o/aev/wVdkvLVRHvSfwZEzx2C7TAkDPX/ycEm9wWrWFbjlKo2wyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:59:51Z"
    mac: ENC[AES256_GCM,data:P8rDFxJbIuAYAusgiifVcME9mUaZlKUOVm58wlqrBP/X8l1zjh7a9I9tFK5iQ1lf6Ct6ug2Dw6+/QGrHEu5r4stQGiPnuGmbeL491Iieejc74VDYabF9Je7TTRQc3QJB1tGN1bMKa92yqHoIOppbknCCZD0uTz/QSZAzg/JFCM8=,iv:aeou2/IULWjZH3H5odvVCil/+6RCc+NPRGQhRFDjlfE=,tag:s2gqmfAmfn+EwYs7gb/gLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
