apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-nextcloud
    namespace: nextcloud
stringData:
    client-secret: ENC[AES256_GCM,data:YXAAq6axAgoS9hwvEe0B/SqAaTrD67uADiyJ5JPdRNYjHLiAQlVXqn5hoZi+BScS,iv:3RtxpS7+RQrzoo6OM+tYcBJfMmIHliV6Qm/09gxxZWA=,tag:9/VgINVC5coO6E9/+D6dVA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSlBxbjQ1b3F0bzNJdzA5
            UEFkeWNFVkN5c3RWcDI0OG9oWW1VNkNlR0hJCjJZVTd3SldqMGlwTlZJd1E4MUc3
            SThEZ1g3K2hvTXhkS3B3ZUdNc2orU2sKLS0tIDZLTHZLdG9idy91NThXR1k2eEtT
            SmptWW1FazUybUFTSlV4NUJOaXJCYjgK0vRVn5u57/p717DBIDxWa7Wp6HwBEu0b
            nwTu7WLqSGgwlg0X84TXPaWMJ4awjo/bPv9vaIpKC93+PqoYYmtzbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:45:53Z"
    mac: ENC[AES256_GCM,data:fclZK28t+fjMAc/w51B6AUzyK9fAzRx7vU5kmymM3IW78nLImEwAVBdjQcnMy3zqLlXN4fKfPkMfe8ztVSjIueX+93ngTDUvorntDIM9RYlXaHzBSP0URrHtn6KJKuub4a0zHArRPt3THXbqebmwIRZoXivaz7wQSSW8QocfE3g=,iv:MLc6VeXrP4MarQYWWyRZ7NqPc+2DwiyYkJMW0TphFYc=,tag:uRb3iO+WeWF5xN7Nh+IdQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-nextcloud
    namespace: keycloak
stringData:
    client-secret: ENC[AES256_GCM,data:QUyR0H0DrDuiV1aMrwlpK1ASh0bGbl/f5zVaPacD11kYt150nPSVrQRQCdyqjG7O,iv:lJ5lpA+ZPdwtItjfzTmIbfY0kSXinpJmCJ7+C6PHV/k=,tag:7ys97ZLVPidI8RmHWWmpTw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSlBxbjQ1b3F0bzNJdzA5
            UEFkeWNFVkN5c3RWcDI0OG9oWW1VNkNlR0hJCjJZVTd3SldqMGlwTlZJd1E4MUc3
            SThEZ1g3K2hvTXhkS3B3ZUdNc2orU2sKLS0tIDZLTHZLdG9idy91NThXR1k2eEtT
            SmptWW1FazUybUFTSlV4NUJOaXJCYjgK0vRVn5u57/p717DBIDxWa7Wp6HwBEu0b
            nwTu7WLqSGgwlg0X84TXPaWMJ4awjo/bPv9vaIpKC93+PqoYYmtzbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:45:53Z"
    mac: ENC[AES256_GCM,data:fclZK28t+fjMAc/w51B6AUzyK9fAzRx7vU5kmymM3IW78nLImEwAVBdjQcnMy3zqLlXN4fKfPkMfe8ztVSjIueX+93ngTDUvorntDIM9RYlXaHzBSP0URrHtn6KJKuub4a0zHArRPt3THXbqebmwIRZoXivaz7wQSSW8QocfE3g=,iv:MLc6VeXrP4MarQYWWyRZ7NqPc+2DwiyYkJMW0TphFYc=,tag:uRb3iO+WeWF5xN7Nh+IdQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
