apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: nextcloud
stringData:
    host: ENC[AES256_GCM,data:EGtrcH1AfWGfpTvjHLYXZWsf7fHoRgs9RI3Wam/VQk816lH7fCLSJA==,iv:8zgmhdNWlis39ye9+Tqds1M0OjBkdt88h67CsbZ2tU4=,tag:CJKtdgiBrgNNcWKpcnOMrQ==,type:str]
    accessKey: ENC[AES256_GCM,data:2imMrF+eOXNm,iv:XuW7RmhnLRZIAGIdw6ZfV2a71a3eUKBiCDR08IO71+8=,tag:HKmgSKY7o0MZSnbYG3rpng==,type:str]
    secretKey: ENC[AES256_GCM,data:NsDfdoZpw/1K,iv:BBNM3hvg2fjwoRt39IjevoBrRLr2V9rVVrJLudr3q3Y=,tag:rWqHQI/XayHKCD3PJ+QA1w==,type:str]
    bucket: ENC[AES256_GCM,data:PQN4dpaXaJun,iv:HdxB5jM5AJnNrvMLXqwBi6UNST4BuSQddg2hGxRRU0Y=,tag:CpeichE1RpF3nzeZpdISxw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bmJVVThhRmcwUTl5Ulky
            a1RBSUdQRzIrYW42eUREUVBvSUc5cEpyN2pjCmlOSG9aT2pMZG1rbUZOdzhSN3da
            Ym1Ndlh4NWdibFNKTEpySll3SG1qS00KLS0tIFN3OFd5NC9PZS9vT0E5VWFxQVVQ
            L0prcHBFNU14R3VSWmhYZy9RMG4vVGcKAHAsosaMqP996v7tD/Re5WogvBOx9kna
            g/P9q4h+SjlcTnvRcdrmobUVC1JyWf+Ndp6K7mPJwGTKEYbb8ep+4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:59:51Z"
    mac: ENC[AES256_GCM,data:NhTfBlzJ6YGh47Yg8VT+7Qc/ugnkA9vEmDlIRfHZHx9MyV8P8GPNnDQNGbljDqWMZz4/GEsLC1wxZ3noUDoorFeSgOfrC5HZJpejIBnb33Cu4X0/iH8915sOu7peVt9OzuHLHpypeqqZtU+raU2PczXrV0/eq+A44iUED4csXG8=,iv:wy6S1Blb9d17zSlIwohfREzpW1HaNVclelXQ6C9M6qw=,tag:dILHOsdALOHMi0lzB7uD8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
