apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: nextcloud
stringData:
    host: ENC[AES256_GCM,data:IZ//EuYukil2qMmg7Teym2tqQTgiYiGZGQ7n4nJxWwynKkXSeO/5LQ==,iv:5exEbX3HQI+/ObaHIHf8U7AqssLP9N0Kniorkm4tF5s=,tag:YXWekRTY2hnhUBcFy/jLpQ==,type:str]
    accessKey: ENC[AES256_GCM,data:cETTM7NGHzu2,iv:AXLMC6FrNeBtHeKXZHrCn9aplaq/FXPsjOM4cX6E1Vc=,tag:bq4dft1/ohGe/b3TYvd4fA==,type:str]
    secretKey: ENC[AES256_GCM,data:Ul15sYnw3v2+,iv:u8i1v/eEn/ObkpD9SGLXKOMFsH9bmUw6TTR6IxZYNrQ=,tag:P7LaM7J54lCApBuOxPNXBQ==,type:str]
    bucket: ENC[AES256_GCM,data:I2DcemEc2OSx,iv:Ad9hn/J3Qy+ZP7AdOB7RA8H5pyF+CEtUzWQcLi6lXrg=,tag:FfqZteAss/FKFUIlnvO8zA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3dIa3pHV25vd0tMdDZS
            bG5UWFZXcDUxbHk2MEFBdktrOXhzdTg4NlM0CjB4TEFMMjc4YkxHbXhsZ0Y2Qi84
            bGY4VGtueDBwaDAzRlVjRDZGbVR2QmMKLS0tIGZsRTVCdnBZaWlLSDFtNzMxM1Rx
            U0hicEk5dFhiQ1A1cmRpUjZ6QUNCSm8KJM1dWQRjLOofM+rP4GP01dcb4hCh+I8u
            rG4qjPUMzfMZsY9fbm4CXHyAEb7MG9ZqQXTm29whEGOzsJJYXtm92w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T07:34:33Z"
    mac: ENC[AES256_GCM,data:uRqHoyO+qbqg/0JV8mGhrfGCGhZGXlVa8wHgU0g/oad/CohWqQ1890eNsqdnjL3s2iKV6+Kl81de4uDn3ZV+1HSZ/adnP9vxITQ7Dr+X8MWz8aGVNM7tplXCtX2lVF4pimWL5OcibRg7ofzUB7XLLIoM7C1fLLMqwNkP4RW3Z2E=,iv:IvF6XTjE/IY6cBBFHSDPHfUjdWC8BvzcTiEwLtYjq3Q=,tag:TtZAVF8WWrIXfUPjQMn35w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
