apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-s3-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    host: ENC[AES256_GCM,data:MSLxTP1KA1O0YFhFT6C0e+2q+Cr7Pe45JPMgFzqMXqKHBUy31gBWMQ==,iv:6/10srKWNGtBQGVUi45KiYFd3EhmkU8TSgoBOqmpANY=,tag:01HlFUOPygBE7CNPHNbVYw==,type:str]
    accessKey: ENC[AES256_GCM,data:c03ZxmskD9bc,iv:KNFd4fEt3JspCidhu5A3ivzOtxSreIM2MscyyKnRGRc=,tag:5tUXvXFWnGwTGTeDsleOVg==,type:str]
    secretKey: ENC[AES256_GCM,data:BIZVLErkD03I,iv:Eiu47NZLzQTxbj3WGIECgwwzqMdkKzOVpioBnUQ3siE=,tag:G1PsyhkYC6otrbLcuCiZCA==,type:str]
    bucket: ENC[AES256_GCM,data:Yai84o32WqeS,iv:j3exAqzLiOQs6WVkNJoEi3Erozm7hbQq8FqCezrPDNc=,tag:USKD/6QH8KyTNs3F+PD47A==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0tUVkxzKzc5YkhDL1Bi
            RTVBcitoamhPZEVWYzR3aGh6TnhyWTQ5WHdJCmhzcWpNbFoyVFE1WkpBRjJuY3dr
            eThuNTBYbFpBczRYMzFtRXRNUG5SVVEKLS0tICtzOGFoNXpOZE8zRVlLekF1c0tW
            SHpNbUZkL1BtNG5hOStjK1NvMDFvVmsK1d0YXL/TzpRgAeBTPhcyilddHVUYjNj4
            ozZunmh37Zp5KNZUfTfoPZwJELMdINY8XoQrgR8ql20LrAqrJ4Dg4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:14:20Z"
    mac: ENC[AES256_GCM,data:ZQesyM12yURmHHNHlD9f3Q6jvCEZtcItoDC11f8fHl6tAmRKWvD5r9EVPgBbzb93siKAuSoJ6IFxtpR+ABVg0ULJKbHlGNVulYTfF7oxo6MqFnmJ6erUNkpMNQo/uBB9W1U5134Axxo0JGzZQ9d7+c4+usZDygHaYN00ScwdEmg=,iv:D386xjYhaU2ddSFXtXhsNhStzVhzrfXvhotT7VkNkzQ=,tag:i8i1vN9ZrWUSV+srbB6G4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-database-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vgpQKOsTwVyF,iv:5VEkbKVYUQ7CcqosS6w5DYvTcxr6bt8X0ReqU291ktE=,tag:VNMd4KBEAJjwTJ1HB/2sNQ==,type:str]
    password: ENC[AES256_GCM,data:G3kGv53Swlyl,iv:+O0u9Pp0n+UO5j3sVjpOh5gvAznfCIl8dGZqCSMkg+I=,tag:/pR+a11UPpVJpFW+WWc2eA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0tUVkxzKzc5YkhDL1Bi
            RTVBcitoamhPZEVWYzR3aGh6TnhyWTQ5WHdJCmhzcWpNbFoyVFE1WkpBRjJuY3dr
            eThuNTBYbFpBczRYMzFtRXRNUG5SVVEKLS0tICtzOGFoNXpOZE8zRVlLekF1c0tW
            SHpNbUZkL1BtNG5hOStjK1NvMDFvVmsK1d0YXL/TzpRgAeBTPhcyilddHVUYjNj4
            ozZunmh37Zp5KNZUfTfoPZwJELMdINY8XoQrgR8ql20LrAqrJ4Dg4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:14:20Z"
    mac: ENC[AES256_GCM,data:ZQesyM12yURmHHNHlD9f3Q6jvCEZtcItoDC11f8fHl6tAmRKWvD5r9EVPgBbzb93siKAuSoJ6IFxtpR+ABVg0ULJKbHlGNVulYTfF7oxo6MqFnmJ6erUNkpMNQo/uBB9W1U5134Axxo0JGzZQ9d7+c4+usZDygHaYN00ScwdEmg=,iv:D386xjYhaU2ddSFXtXhsNhStzVhzrfXvhotT7VkNkzQ=,tag:i8i1vN9ZrWUSV+srbB6G4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bMeJVNIkQdFO,iv:MQ0XyTHLEi4eBZ8jlbGcXQUOkWgBUrQ8EHIr9Xyjw+8=,tag:q7r1Ssos8mqylksb9RVs7w==,type:str]
    password: ENC[AES256_GCM,data:o8jgreW3Fj+V,iv:EL50fNF0dINIxJl0930QWe7MzyAoRaxbhfC511JiLXg=,tag:Li2/5c8QrF6zOXldY3lX+A==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0tUVkxzKzc5YkhDL1Bi
            RTVBcitoamhPZEVWYzR3aGh6TnhyWTQ5WHdJCmhzcWpNbFoyVFE1WkpBRjJuY3dr
            eThuNTBYbFpBczRYMzFtRXRNUG5SVVEKLS0tICtzOGFoNXpOZE8zRVlLekF1c0tW
            SHpNbUZkL1BtNG5hOStjK1NvMDFvVmsK1d0YXL/TzpRgAeBTPhcyilddHVUYjNj4
            ozZunmh37Zp5KNZUfTfoPZwJELMdINY8XoQrgR8ql20LrAqrJ4Dg4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:14:20Z"
    mac: ENC[AES256_GCM,data:ZQesyM12yURmHHNHlD9f3Q6jvCEZtcItoDC11f8fHl6tAmRKWvD5r9EVPgBbzb93siKAuSoJ6IFxtpR+ABVg0ULJKbHlGNVulYTfF7oxo6MqFnmJ6erUNkpMNQo/uBB9W1U5134Axxo0JGzZQ9d7+c4+usZDygHaYN00ScwdEmg=,iv:D386xjYhaU2ddSFXtXhsNhStzVhzrfXvhotT7VkNkzQ=,tag:i8i1vN9ZrWUSV+srbB6G4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
