apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    host: ENC[AES256_GCM,data:ZP/GBkSb4TdlwjornfSXxD90P0O1F7nNC8cjb4ArHvydFXd2jVEOaw==,iv:XvW3409r4vlJoWG558humOGKl4O85BFvIAaWoqg+S4U=,tag:/t61aTd/abF29m9UBZKFzA==,type:str]
    accessKey: ENC[AES256_GCM,data:4N2fxRmGBH2+,iv:cjniIkC1MOA1oRjSxcWKFEc/x24Jo7rDwd4SnrqNMZo=,tag:Ar39gf2jEU9bz/Qma9UbKQ==,type:str]
    secretKey: ENC[AES256_GCM,data:vKkA81FVCQ7q,iv:uzePN39yQQ8P9j4bVSq8i41BDKOdVOkwRzWzHjTJpVY=,tag:ZSr8odvnKmFcqxpbbQgz6g==,type:str]
    bucket: ENC[AES256_GCM,data:SBxOncKcqR4m,iv:Xp2jaATnh3z/+QpRfDiIergm3schAZSaRtb9EQ9+QQk=,tag:esHcnM1CcC55zGoVcdjcTA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySWdQU3pwMG8zN2psbGpX
            aWE0S0lHMmVKOW9jcCtPOGUvTU13TnZqUlFvCmhveDVQenpRV0s2UklJdlVaT25s
            MmtseGRWTGxLeTJRSytERzhDUUZpY2sKLS0tIHV3N205eXZES3RFUDREeERFNE5T
            dVBWSjRrQ2FLNFpPMVZ4SEdudks2U3MKD8YVJuHRK1rxGPEuImEHDB5NpG3m627M
            qjatGadhUfxkkZ34h3tfwJZoYeE1QUvWULMKCUhWqX9j7vnPKy8urA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T06:56:51Z"
    mac: ENC[AES256_GCM,data:r7UnTdPGKNTgTX4ArX1fnZkIEGR9uSY/cJXneWLsNpFRJ6YNuWmGPza1+EGjbwbeT6bI+0/Hn8CkfBa7opikPtSzoZB+5lZGpPqrEErH1jYMnFC3UATzNEczDC0++pAjyk1vG1rnXo4cqjtkwOkRG0GY7hO6/V4aVSdWFucKLLc=,iv:yV2StlvR96zv/OK/JbLakTmXd5IPGq3tu5vWrlE7UYI=,tag:x/heeeHHA9qdW1ZKmdfv0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-database-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:31Elvq2TkOr6,iv:AQnQimyaepoLyfYuD9RpIZ+Vu4pY09b4VV++bnbYtkg=,tag:nI6GLTByqF/GOmrI5LGS/g==,type:str]
    password: ENC[AES256_GCM,data:GD+zo/CUriY1,iv:GYIeXXv2OGIa0SQxOI+GjQ27LYtOHFcLxhz3vVcInGU=,tag:Naa+ATKC4ubRXyi5EtJCEw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySWdQU3pwMG8zN2psbGpX
            aWE0S0lHMmVKOW9jcCtPOGUvTU13TnZqUlFvCmhveDVQenpRV0s2UklJdlVaT25s
            MmtseGRWTGxLeTJRSytERzhDUUZpY2sKLS0tIHV3N205eXZES3RFUDREeERFNE5T
            dVBWSjRrQ2FLNFpPMVZ4SEdudks2U3MKD8YVJuHRK1rxGPEuImEHDB5NpG3m627M
            qjatGadhUfxkkZ34h3tfwJZoYeE1QUvWULMKCUhWqX9j7vnPKy8urA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T06:56:51Z"
    mac: ENC[AES256_GCM,data:r7UnTdPGKNTgTX4ArX1fnZkIEGR9uSY/cJXneWLsNpFRJ6YNuWmGPza1+EGjbwbeT6bI+0/Hn8CkfBa7opikPtSzoZB+5lZGpPqrEErH1jYMnFC3UATzNEczDC0++pAjyk1vG1rnXo4cqjtkwOkRG0GY7hO6/V4aVSdWFucKLLc=,iv:yV2StlvR96zv/OK/JbLakTmXd5IPGq3tu5vWrlE7UYI=,tag:x/heeeHHA9qdW1ZKmdfv0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0nx6MvbEnScr,iv:Gme5TQzRvlv9uU2Lvo+k4dIDqgCzO+2jHGQlSWHMheg=,tag:YgCQ7keMHulZlsp5y5eErw==,type:str]
    password: ENC[AES256_GCM,data:VNZUCD/QYXrX,iv:T47W4N5YhztmsuQAgMOmfAG6ko/xcxW8mLm88gvp7pg=,tag:3zc+qG1cOG6y9AA6xVT2pA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySWdQU3pwMG8zN2psbGpX
            aWE0S0lHMmVKOW9jcCtPOGUvTU13TnZqUlFvCmhveDVQenpRV0s2UklJdlVaT25s
            MmtseGRWTGxLeTJRSytERzhDUUZpY2sKLS0tIHV3N205eXZES3RFUDREeERFNE5T
            dVBWSjRrQ2FLNFpPMVZ4SEdudks2U3MKD8YVJuHRK1rxGPEuImEHDB5NpG3m627M
            qjatGadhUfxkkZ34h3tfwJZoYeE1QUvWULMKCUhWqX9j7vnPKy8urA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T06:56:51Z"
    mac: ENC[AES256_GCM,data:r7UnTdPGKNTgTX4ArX1fnZkIEGR9uSY/cJXneWLsNpFRJ6YNuWmGPza1+EGjbwbeT6bI+0/Hn8CkfBa7opikPtSzoZB+5lZGpPqrEErH1jYMnFC3UATzNEczDC0++pAjyk1vG1rnXo4cqjtkwOkRG0GY7hO6/V4aVSdWFucKLLc=,iv:yV2StlvR96zv/OK/JbLakTmXd5IPGq3tu5vWrlE7UYI=,tag:x/heeeHHA9qdW1ZKmdfv0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
