{{- if eq .Values.mode "leaf" }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.leaf.name }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  syncPolicy:
    preserveResourcesOnDeletion: true

  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.repoURL | quote }}
              revision: {{ .Values.targetRevision | quote }}
              requeueAfterSeconds: 30
              files:
                - path: {{ .Values.leaf.file | quote }}

          - list:
              elementsYaml: |
                {{ `{{- $items := list }}` }}
                {{ `{{- range .` }}{{ .Values.leaf.listKey }}{{ ` }}` }}
                {{ `{{- if (dig "enabled" true .) }}` }}
                {{ `{{- $items = append $items . }}` }}
                {{ `{{- end }}` }}
                {{ `{{- end }}` }}
                {{ `{{ $items | toYaml }}` }}

  template:
    metadata:
      name: '{{ `{{ .name }}` }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default

  templatePatch: |
    metadata:
      annotations:
        {{ `{{- if hasKey . "priority" }}` }}
        argocd.argoproj.io/sync-wave: "{{ `{{ .priority }}` }}"
        {{ `{{- end }}` }}
    spec:
      syncPolicy:
        {{ `{{- if (dig "syncPolicy" "automated" false .) }}` }}
        automated:
          prune: true
          selfHeal: true
        {{ `{{- end }}` }}
        syncOptions:
          - CreateNamespace=true
          {{ `{{- range (dig "syncPolicy" "syncOptions" (list) .) }}` }}
          - {{ `{{ . }}` }}
          {{ `{{- end }}` }}
      destination:
        namespace: {{ `{{ dig "namespace" .name . }}` }}
      sources:
        {{ `{{- if hasKey . "repoURL" }}` }}
        - repoURL: {{ `{{ .repoURL }}` }} 
          targetRevision: {{ `{{ .targetRevision }}` }} 

          {{ `{{- with .chartPath }}` }}
          path: {{ `{{ . }}` }}
          {{ `{{- end -}}` }}

          {{ `{{- with .chartName }}` }}
          chart: {{ `{{ . }}` }} 
          {{ `{{- end -}}` }}
          
          {{ `{{- if not (or (hasKey . "chartPath") (hasKey . "chartName")) }}` }}
          chart: {{ `{{ .name }}` }}
          {{ `{{- end }}` }}

          {{ `{{- if hasKey . "chartValues" }}` }}
          helm:
            valueFiles:
              - {{ `{{ .chartValues }}` }}
          {{ `{{- end -}}` }}
        {{ `{{- end -}}` }}

        {{ `{{- with .kustomize }}` }}
        - repoURL: {{ $.Values.repoURL | quote }}
          targetRevision: {{ $.Values.targetRevision | quote }}
          path: {{ `{{ .path }}` }}
        {{ `{{- end -}}` }}

        {{ `{{- if .manifests }}` }}
        - repoURL: {{ $.Values.repoURL | quote }}
          targetRevision: {{ $.Values.targetRevision | quote }}
          path: {{ `{{ .path }}` }}
          directory:
            recurse: true
        {{ `{{- end -}}` }}

{{- end }}
