{{- if eq .Values.mode "leaf" }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.leaf.name }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  syncPolicy:
    preserveResourcesOnDeletion: true

  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.repoURL | quote }}
              revision: {{ .Values.targetRevision | quote }}
              requeueAfterSeconds: 30
              files:
                - path: {{ .Values.leaf.file | quote }}

          - list:
              elementsYaml: |
                {{ `{{- $items := list }}` }}
                {{ `{{- range .` }}{{ .Values.leaf.listKey }}{{ ` }}` }}
                {{ `{{- if (dig "enabled" true .) }}` }}
                {{ `{{- $items = append $items . }}` }}
                {{ `{{- end }}` }}
                {{ `{{- end }}` }}
                {{ `{{ $items | toYaml }}` }}

  template:
    metadata:
      name: '{{ `{{ .name }}` }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: default

  templatePatch: |
    metadata:
      annotations:
        {{ `{{- if hasKey . "priority" }}` }}
        argocd.argoproj.io/sync-wave: "{{ `{{ .priority }}` }}"
        {{ `{{- end }}` }}
    spec:
      syncPolicy:
        {{ `{{- if (dig "syncPolicy" "automated" false .) }}` }}
        automated:
          prune: true
          selfHeal: true
        {{ `{{- end }}` }}
        syncOptions:
          - CreateNamespace=true
          {{ `{{- range (dig "syncPolicy" "syncOptions" (list) .) }}` }}
          - {{ `{{ . }}` }}
          {{ `{{- end }}` }}
      destination:
        namespace: {{ `{{ dig "namespace" .name . }}` }}
      sources:
        {{ `{{- range .sources }}` }}

        {{ `{{- if eq .type "values"}}` }}
        - repoURL: {{ `{{ .repoURL | quote }}` }}
          targetRevision: {{ `{{ .targetRevision | quote }}` }}
          ref:  {{ `{{ .ref }}` }}

        {{ `{{- else if eq .type "helm"}}` }}
        - repoURL: {{ `{{ .repoURL | quote }}` }}
          targetRevision: {{ `{{ .targetRevision | quote }}` }}

          {{ `{{- if hasKey . "chart" }}` }}
          chart:  {{ `{{ .chart | quote }}` }}
          {{ `{{- end }}` }}

          {{ `{{- if hasKey . "path" }}` }}
          path: {{ `{{ .path | quote }}` }}
          {{ `{{- end }}` }}

          {{ `{{- with .valueFiles }}` }}
          helm:
            valueFiles:
            {{ `{{- range . }}` }}
            - {{ `{{ . | quote }}` }}
            {{ `{{- end }}` }}
          {{ `{{- end }}` }}

        {{ `{{- else if eq .type "manifest"}}` }}
        - repoURL: {{ `{{ .repoURL | quote }}` }}
          targetRevision: {{ `{{ .targetRevision | quote }}` }}
          path:  {{ `{{ .path | quote }}` }}
          directory:
            recurse: {{ `{{ .recurse | default true }}` }}

        {{ `{{- else if eq .type "kustomize"}}` }}
        - repoURL: {{ `{{ .repoURL | quote }}` }}
          targetRevision: {{ `{{ .targetRevision | quote }}` }}
          path:  {{ `{{ .path | quote }}` }}
        {{ `{{- end }}` }}

        {{ `{{- end }}` }}

{{- end }}
