apiVersion: v1
kind: Secret
metadata:
    name: keycloak-database-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Hwh/kBk=,iv:H9q2R+l/eViABc1wZSlw/i5KlynGqb7syJ8cZSnX6go=,tag:8W8qEeg4jwM8dOCYyEtFKA==,type:str]
    password: ENC[AES256_GCM,data:N6uDOzc=,iv:R4EaFU3vATuJXEXxtvMaIPMhSET7Qs1Tb+btsbcHvSg=,tag:yLDbKWcYRkwX7O/RRnownQ==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YnBIbFloV3VFTkowVXpz
            eDE2c3R0Z2tIcXV1SUlFMytyRWZLbmR6Qm1FCjlDOHJ6RmtCaWlqL3Q0ME4rZnp4
            QnZKR2JZN09pbFg0QlIwWHlyaEk3eW8KLS0tIE9UelAwdStVTDRmZ3Fpc1VGL3Bx
            R0xGUUtiWTZncGs5VEgraGg4TjRZa28Kc/c0OOD7CTXMHhXZNf1UGJFLpEArwr4n
            48bpdaTz3Hr9qKJpG/8O7M9d8HTtOpjio7EyVpzbCAp2RMYs5RGSFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T20:04:54Z"
    mac: ENC[AES256_GCM,data:zwdhEMuKD5oMNYhGbpXk9rx2NC+/rAaY1Bgv1f3BtKuHWIW+pxD73ZyCXTsfY1TatdNp9deaAnpWqBX3IJebvSirfy5dYa6rTEcv97zIiRdBrewYEBRuV34wpLmout76tqRo7a1PJT6TLGhGqZmPb/eKEpHBgsFFlF+kLASNHcU=,iv:JUCbmty2+3L22GdT+x9bJVnsYfPldLQh9xY7XYJHKro=,tag:VCDpEWWFREhJnJ3HZ7OG9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0A8IU44=,iv:fqzTRO8FjlDXZw3StC+IwcBCXZaVS6JYU6HW+mJZXKQ=,tag:JdzPjEGz/9xs2pdL4pF6rA==,type:str]
    password: ENC[AES256_GCM,data:WfUuivg=,iv:nu+dmuLHo/CL77SPUGm0n0yAkTp2Pf/3P7hr6jQiwZY=,tag:4UIEnrA7o0UflJv2Dv54ZA==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YnBIbFloV3VFTkowVXpz
            eDE2c3R0Z2tIcXV1SUlFMytyRWZLbmR6Qm1FCjlDOHJ6RmtCaWlqL3Q0ME4rZnp4
            QnZKR2JZN09pbFg0QlIwWHlyaEk3eW8KLS0tIE9UelAwdStVTDRmZ3Fpc1VGL3Bx
            R0xGUUtiWTZncGs5VEgraGg4TjRZa28Kc/c0OOD7CTXMHhXZNf1UGJFLpEArwr4n
            48bpdaTz3Hr9qKJpG/8O7M9d8HTtOpjio7EyVpzbCAp2RMYs5RGSFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T20:04:54Z"
    mac: ENC[AES256_GCM,data:zwdhEMuKD5oMNYhGbpXk9rx2NC+/rAaY1Bgv1f3BtKuHWIW+pxD73ZyCXTsfY1TatdNp9deaAnpWqBX3IJebvSirfy5dYa6rTEcv97zIiRdBrewYEBRuV34wpLmout76tqRo7a1PJT6TLGhGqZmPb/eKEpHBgsFFlF+kLASNHcU=,iv:JUCbmty2+3L22GdT+x9bJVnsYfPldLQh9xY7XYJHKro=,tag:VCDpEWWFREhJnJ3HZ7OG9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
