apiVersion: v1
kind: Secret
metadata:
    name: keycloak-database-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:BipqfroT,iv:uYDUUdVFZfCwGLZsegPr1xfxWMa67X9YOSyELKBxPHM=,tag:gtlZe7uGYzaRuAu9ekYQXw==,type:str]
    password: ENC[AES256_GCM,data:wKmemRwmpkiD,iv:E1aetDlotjeT4T3uJoRQ/euQ/KbOza/HHt0gfK/hf24=,tag:QEY6LthrvMoPMbNyV11TsA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMlcrZXZrZVBkYUN5bjJ5
            QUl5L0ZiZGtPeHdHTmxpanRKM0xmVWFqOTJJCjRLUGJqVUovZExyWHNTM0hsbGRL
            OGxEZTkrMUxPSlp2dnY4MlBGUm13RGMKLS0tIHNlT0VhZUxuUk1HZGNmM1grUThy
            cFlGY0dZa2E2WEJLN24rMU1TZnAwNGsKR/2lDz4K/wdIcVMu55D/WI7FuZT4R3zI
            NWB/46z2dPkL7a4STw980a5gtY4RdJwia5sIiOyrh/doZPel0xhZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:31:15Z"
    mac: ENC[AES256_GCM,data:UW91EeZzx1SJ1QDXmYY2fyPA/Ez+4ttkRxP1fcgDPBE1w6BFJgXVfOLzFGxJsSKFo5zVypgBuQ5rESrgBOFU1ZkaAEO0/o+ESh7yXPiObasATxlScLOJhq/qRq78zJhubPhPmFgtQerkihG1HqnqlOkcwajuDTcKRnBTn3O1MIY=,iv:IUzJcO93saBKsRnpaDFTFTHfuAZfw8PqFt7YnTx29Xc=,tag:69JkkGkYCOWZR/leWMy5Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LjjEh6QO,iv:LAa6BOLiTCTxbinc3JchUI1GAlAHmz8EQ54Oas42/7k=,tag:SgIREjRxJFxRCWJjlw/jPA==,type:str]
    password: ENC[AES256_GCM,data:25UWufvYjcED,iv:AB9vlRbQ1Vfy3HiuE8GwtHnI+QBSGdHEqBvVDaef3XE=,tag:U/oUmXdyUJ9i1HTagS6mOA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMlcrZXZrZVBkYUN5bjJ5
            QUl5L0ZiZGtPeHdHTmxpanRKM0xmVWFqOTJJCjRLUGJqVUovZExyWHNTM0hsbGRL
            OGxEZTkrMUxPSlp2dnY4MlBGUm13RGMKLS0tIHNlT0VhZUxuUk1HZGNmM1grUThy
            cFlGY0dZa2E2WEJLN24rMU1TZnAwNGsKR/2lDz4K/wdIcVMu55D/WI7FuZT4R3zI
            NWB/46z2dPkL7a4STw980a5gtY4RdJwia5sIiOyrh/doZPel0xhZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:31:15Z"
    mac: ENC[AES256_GCM,data:UW91EeZzx1SJ1QDXmYY2fyPA/Ez+4ttkRxP1fcgDPBE1w6BFJgXVfOLzFGxJsSKFo5zVypgBuQ5rESrgBOFU1ZkaAEO0/o+ESh7yXPiObasATxlScLOJhq/qRq78zJhubPhPmFgtQerkihG1HqnqlOkcwajuDTcKRnBTn3O1MIY=,iv:IUzJcO93saBKsRnpaDFTFTHfuAZfw8PqFt7YnTx29Xc=,tag:69JkkGkYCOWZR/leWMy5Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
