apiVersion: v1
kind: Secret
metadata:
    name: keycloak-database-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:r7CP7MY=,iv:IMFmbbA6NYfoRbADyStZhO/NpFUZCwqZKNkO8XE24Lw=,tag:ujUd67NaXFdc28jYIP3KFQ==,type:str]
    password: ENC[AES256_GCM,data:axX8ggw=,iv:BHhJq6o1ZFJ2eoKBxkWDsi5MpY5ICj7sQJZMQapX5QA=,tag:iiscC3X/bD17126obzsU0w==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzam9jTm9qbjNwZ0FPVkc1
            QnBtSFNNeUNEcmNucklJc1did3hieDBYZm5BClhmQllvcXd3SnFCeVMwb1lvd3V1
            RXlRdkJIT2IvTGFLZGUwSFBvTHM0a3cKLS0tIGVDZTI0ZHZlcVAwQysyaTVxZVd3
            bU94UU1YZ3N4VzBJZG9iK2w0WGNWTE0K3AEmKIV1/fSl9xWUXH4uNH/DcSxNlatA
            bCGod6ZOOOO5RTucOITVDF/8Q8CaAE4tDvBvf1FLoI/EI40GH21v7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T20:22:05Z"
    mac: ENC[AES256_GCM,data:zc04NS9JBO7jxkbOdlMVoI6sd8muelnPoAHB7Ts39dJq3E42AP0wx0OufltHjOEP5vo55FNy8jgQLV9gCKKcMrfam6spqqgfRosxd1J94d/4Kkar3wQajCxYjbPCu/BoTljryIord6KYVXSiZFZMMHcgBSEfiXjXv66H7yArnJc=,iv:ix8lv4dvc5QDkfEw/SP+QxuV/uJp1PHVHIMt59b5y3c=,tag:6uFvbx+6GVl38b5zlxL/mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:S2OQW2s=,iv:xrKlCL81X16Ac8n1ODGogYiu6t/CTBssi+armrl6EfY=,tag:Dt7Kh4GgbffI/Lyp9wtItQ==,type:str]
    password: ENC[AES256_GCM,data:PoKwaZI=,iv:zmP68MFY7w3VpdKr8u30v0bMNOIBoCcPgpHpHPHcfJA=,tag:083iO5YYfMgsQwSLrE2Q8Q==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzam9jTm9qbjNwZ0FPVkc1
            QnBtSFNNeUNEcmNucklJc1did3hieDBYZm5BClhmQllvcXd3SnFCeVMwb1lvd3V1
            RXlRdkJIT2IvTGFLZGUwSFBvTHM0a3cKLS0tIGVDZTI0ZHZlcVAwQysyaTVxZVd3
            bU94UU1YZ3N4VzBJZG9iK2w0WGNWTE0K3AEmKIV1/fSl9xWUXH4uNH/DcSxNlatA
            bCGod6ZOOOO5RTucOITVDF/8Q8CaAE4tDvBvf1FLoI/EI40GH21v7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T20:22:05Z"
    mac: ENC[AES256_GCM,data:zc04NS9JBO7jxkbOdlMVoI6sd8muelnPoAHB7Ts39dJq3E42AP0wx0OufltHjOEP5vo55FNy8jgQLV9gCKKcMrfam6spqqgfRosxd1J94d/4Kkar3wQajCxYjbPCu/BoTljryIord6KYVXSiZFZMMHcgBSEfiXjXv66H7yArnJc=,iv:ix8lv4dvc5QDkfEw/SP+QxuV/uJp1PHVHIMt59b5y3c=,tag:6uFvbx+6GVl38b5zlxL/mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
