apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: openldap
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:B4xHKqSMp4pK,iv:ohuZ9VJeWTDtQYOCpNt4zqgfcho+a/iItRCiCxLACYM=,tag:IslUPnEWPVevjmHOuCJqbQ==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:M3PToriimqLN,iv:ye5uey2dNsT3fUjFbxgDrTHc2RORdRSH+rCpnUHjX/k=,tag:k6j5AkS9xBLB/pGIMR99Lw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUEowZXFBa2VmQzdSWkNt
            OFBQeUJabGJmNUZmb0EzTlA0UFdYM3hXVHlzCkpHdVJCNUtkMnphcytDbXFGVVUz
            YUVkbzBTUENNbEM4L0xXaUczTkgzUVEKLS0tIHpjRWUzUXVCY2c3bXIvUy9MVjE0
            alFUWW5JYlVoY01DK042TCtBUm9ZRVEK+FJD/aVq/Fj81gBlPsSWnMjlEIwEG/xu
            sQx4y3MInZPTAQ/JAVcIWQImEBxG/dPZtkSEf58YgQ4LAMREbHlxow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:29:12Z"
    mac: ENC[AES256_GCM,data:tjcUL6rS86HpgRVJOVdCjWScgUQx4bBIeH6fR5Zz6N68OQsrWHO/yB4l1Q4ZYgmMLYOKRldylyeXfMuKQ62cAjZ96mYbrAGBUTrlNsAnCqO5GKTX5ZiWftFBp8u0pfuLpgXBD2dfPbh9QFdu1OqEtrTj2/F/D0mZmk4PpdrLSR4=,iv:1cChNFeOtsAbstm0iy/pR3p38rqczd3eL5ACZlTzCc0=,tag:r9HZPiZ6jTd2NBpCDih0tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
