apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: openldap
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:cj/oSNS8sfup,iv:ylMB+3vqsFBs8QFd+n1tULgmrRBuQ2JwZ0cS1Evj8GE=,tag:cHz5O+yV07w4Z3XLBdTewQ==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:tSHraE70Qogv,iv:7uzoDSXuV8RRw3u31iyHGSjM1ltQJfJfeFGqcErbICw=,tag:8M9A+YoW2Ng/WuxS6WmeTg==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOXl6YmpIdEVzNk9uaksy
            bldrNVA3SWhhRWR5R1h4d2ZsZWN4ZGg1QWdBCkFrRzgxREVUQllnWGxLTHJLS25h
            M3RCS29TWkJ4ZGZMaVRqV0s4cmUvZ2MKLS0tIDM0ZXYwQi84MHlISHZtWWtsSGRS
            Z0UrYlJLR1hwUW96QysvWklWSkJsd0kK9IIIlWxxrujikztUU8RB7023da7WupsZ
            BNaag5k8akyD7IAMFK5hDas/SWxCUUXnrh6Er//hFf6C5DOoicOeFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T18:00:04Z"
    mac: ENC[AES256_GCM,data:WS0mRO2IKkux4Hoyl6aDNaomBPUf6OH77wnRJLtKjLcSxB7SllqFzSP4S9qtY0koRlhguJ870yOvkzE9+G79eqP0WQStwsbB50X2d+obenCjZ6obAaClyKZjPryoN70DJaJjX4utmbnNqJyuWl8zOjvFB4ieDUCgbnU5239hU34=,iv:01aaQ5NFk0m56S2DETbs2dVmU2FaWGxy6LXozjmBJWA=,tag:9GHR58puUdirQLtXGm5UIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
