{{- if eq .Values.mode "node" }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.node.name | quote }}
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.repoURL | quote }}
              revision: {{ .Values.targetRevision | quote }}
              requeueAfterSeconds: 30
              files:
                - path: {{ .Values.node.file | quote }}

          - list:
              elementsYaml: |
                {{ `{{- $items := list }}` }}
                {{ `{{- range .` }}{{ .Values.node.listKey }}{{ ` }}` }}
                {{ `{{- if (dig "enabled" true .) }}` }}
                {{ `{{- $items = append $items . }}` }}
                {{ `{{- end }}` }}
                {{ `{{- end }}` }}
                {{ `{{ $items | toYaml }}` }}

  template:
    metadata:
      name: ""
    spec:
      project: default 
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd

  templatePatch: |
    metadata:
      #name: "{{ $.Values.node.product}}-{{ `{{ .name }}` }}"
      name: "{{ `{{ .name }}` }}"
      annotations:
        {{ `{{- if hasKey . "priority" }}` }}
        argocd.argoproj.io/sync-wave: "{{ `{{ .priority }}` }}"
        {{ `{{- end }}` }}
      labels:
        application: "{{ `{{ .name }}` }}"
        product: {{ $.Values.node.product | quote }}

    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ `{{ dig "namespace" "name" .name . }}` }}"

      syncPolicy:
        {{ `{{- if eq (toString (dig "syncPolicy" "automated" "false" .)) "true" }}` }}
        automated:
          prune: true
          selfHeal: true
        {{ `{{- end }}` }}

        {{ `{{- with (dig "namespace" "labels" dict .) }}` }}
        managedNamespaceMetadata:
          labels:
            {{ `{{- range $key, $value := . }}` }}
            {{ `{{ $key }}` }}: {{ `{{ $value | toString | quote }}` }}
            {{ `{{- end }}` }}
        {{ `{{- end }}` }}

        syncOptions:
          {{ `{{- if eq (toString (dig "namespace" "autocreate" "false" .)) "true" }}` }}
          - CreateNamespace=true
          {{ `{{- end }}` }}
          {{ `{{- range (dig "syncPolicy" "syncOptions" (list) .) }}` }}
          - {{ `{{ . }}` }}
          {{ `{{- end }}` }}

      sources:
        - repoURL: {{ $.Values.repoURL | quote }}
          targetRevision: {{ $.Values.targetRevision | quote }}
          path: {{ $.Values.node.childChartPath | quote }}
          helm:
            values: |
              mode: {{ $.Values.node.childMode | quote }}
              repoURL: {{ $.Values.repoURL | quote }}
              targetRevision: {{ $.Values.targetRevision | quote }}
              name: "{{ `{{ .name }}` }}"
              leaf:
                #name: {{ $.Values.node.childNameTemplate | replace "{{ product }}" $.Values.node.product | replace "{{ application }}" "{{ .name }}" | quote }}
                name: {{ `{{ .name }}` }}
                file: {{ $.Values.node.childFileTemplate | replace "{{ product }}" $.Values.node.product | replace "{{ application }}" "{{ .name }}" | quote }}
                product: {{ $.Values.node.product | quote }}
                application: {{ `{{ .name }}` | quote }}
                {{ `{{- with .namespace }}` }}
                namespace:
                  {{ `{{- toYaml . | nindent 14 }}` }}
                {{ `{{- end }}` }}
{{- end }}
