# ===============================================
#   ____                __      __        
#  / __ \___  ___ ___  / /  ___/ /__ ____ 
# / /_/ / _ \/ -_) _ \/ /__/ _  / _ `/ _ \
# \____/ .__/\__/_//_/____/\_,_/\_,_/ .__/
#     /_/                          /_/    
#
# : OpenLDAP (application)
# ===============================================
#
# -----------------------------------------------
# @section common parameters
# -----------------------------------------------
#
# @param nameOverride      : String to partially override common.names.name
# @param fullnameOverride  : String to fully override common.names.fullname
# @param namespaceOverride : String to fully override common.names.namespace
# @param commonLabels      : Labels to add to all deployed objects
# @param commonAnnotations : Annotations to add to all deployed objects
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}

# -----------------------------------------------
# @section openldap parameters
# -----------------------------------------------

openldap:
 
  # ===============================================
  # @section OpenLDAP Configuration parameters
  # =============================================== 
  #
  # @param openldap.configuration.organization                       : LDAP organization name.
  # @param openldap.configuration.domain                             : LDAP domain name.
  # @param openldap.configuration.baseDN                             : LDAP base distinguished name.
  # @param openldap.configuration.existingSecret.enabled             : Use an existing Kubernetes Secret for LDAP passwords.
  # @param openldap.configuration.existingSecret.name                : Name of the existing Kubernetes Secret.
  # @param openldap.configuration.existingSecret.keys.adminPassword  : Secret key containing the LDAP admin password.
  # @param openldap.configuration.existingSecret.keys.configPassword : Secret key containing the LDAP config admin password.
  configuration:

    organization: "Anyekey pl"
    domain: "anykey.pl"
    baseDN: "dc=anykey,dc=pl"

    existingSecret:
      enabled: true 
      name: openldap-admin-secret
      keys:
        adminPassword: LDAP_ADMIN_PASSWORD
        configPassword: LDAP_CONFIG_PASSWORD

    # ------------------------------------------
    # @subsection TLS parameters 
    # ------------------------------------------
    #
    # @param openldap.configuration.tls.enabled : Enable TLS support for OpenLDAP.   
    tls:
      enabled: true
      secretName: openldap-tls-secret

