# ===============================
# 
# ===============================
applications:

  # ------------------
  # Podinfo
  # ------------------

    - name: podinfo
      enabled: true

      # -- Global Namespace 
      namespace:
        name: nextcloud
        autocreate: "true"
        labels:
          shared-s3-creds: "true"

      # -- Global Sync
      syncPolicy:
        automated: true

  # ------------------
  # Something 
  # ------------------

  #    - name: something 
