# ===============================
# 
# ===============================
applications:

  # ------------------
  # Podinfo
  # ------------------

    - name: podinfo

  # ------------------
  # Something 
  # ------------------

  #    - name: something 
