apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
  name: app-data
spec:
  clusterRef:
    name: seaweed1
    namespace: seaweedfs

  versioning: Enabled

  quota:
    enabled: true
    size: 10Gi

  owner: app-user

  access:
    - user: app-user
      actions:
        - Read
        - Write
        - List
