apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1
  hostSuffix: seaweed.anykey.pl

  master:
    replicas: 3
    volumeSizeLimitMB: 1024

  volume:
    replicas: 1
    requests:
      storage: 2Gi
    rack: "rack1"
    dataCenter: "dc1"

  filer:
    replicas: 1
    #s3:
    #  enabled: true
    #iam: true
    #extraArgs:
    #  - "-s3.iam.config=/etc/seaweedfs/iam/iam.json"
    #  - "-s3.iam.readOnly=false"
    #volumes:
    #  - name: iam-config
    #    secret:
    #      secretName: seaweed-iam-config
    #volumeMounts:
    #  - name: iam-config
    #    mountPath: /etc/seaweedfs/iam
    #    readOnly: true
---
