apiVersion: v1
kind: Secret
metadata:
  name: seaweed-iam-config
  namespace: seaweedfs-operator
type: Opaque
stringData:
  iam.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "admin",
              "secretKey": "admin"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write",
            "List"
          ]
        }
      ]
    }
