{{- if .Values.appStorage.blob.enabled }}
{{- $root := . }}
{{- $fullname := include "common.names.fullname" . }}
{{- $baseName := default $fullname .Values.appStorage.blob.secretHelper.name }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret" $baseName | quote }}
  namespace: {{ default (include "common.names.namespace" .) .Values.appStorage.blob.namespace  | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" $baseName | quote }}

  target:
    name: {{ default (printf "%s-object-store-secret" (include "common.names.fullname" .)) .Values.appStorage.blob.secretHelper.externalSecret.secretName | quote }}
    creationPolicy: {{ .Values.appStorage.blob.secretHelper.externalSecret.target.creationPolicy }}
    template:
      engineVersion: {{ .Values.appStorage.blob.secretHelper.externalSecret.target.template.engineVersion }}
      type: {{ .Values.appStorage.blob.secretHelper.externalSecret.target.template.type }}
      data:
        {{- toYaml .Values.appStorage.blob.secretHelper.externalSecret.target.template.data | nindent 8 }}

  data:
  {{- with .Values.appStorage.blob.secretHelper.externalSecret.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ default (printf "%s-object-store-secret-raw" (include "common.names.fullname" $root )) .remoteRef.key | quote }}
        property: {{ .remoteRef.property | quote }} 
  {{- end }}
{{- end }}
