{{- if .Values.appStorage.blob.enabled }}
{{- $fullname := include "common.names.fullname" . }}
{{- $baseName := default $fullname .Values.appStorage.blob.secretHelper.name }}
{{- $namespace := default (include "common.names.namespace" .) .Values.appStorage.blob.namespace  | quote }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ printf "%s-secret-store" $baseName | quote }}
  namespace: {{ $namespace }} 
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $namespace }} 
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ printf "%s-sa" $baseName | quote }}
{{- end }}
