# ===============================
# 
# ===============================
applications:

  # ------------------
  # keycloak-opertator (manage instances)
  # ------------------

  - name: keycloak-operator
    namespace: keycloak

    enabled: true
    priority: -5

    syncPolicy:
      automated: false

    sources:

      # Keycloak prefers OLM installation method
      - type: manifests
        repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
        targetRevision: 26.6.1
        path: kubernetes/

  # ------------------
  # edp-keycloak-operator (manage clients) 
  # ------------------
  
  - name: edp-keycloak-operator 
    namespace: keycloak

    enabled: true
    priority: -5

    syncPolicy:
      automated: false

    sources:

      - type: values
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        ref: values

      - type: helm 
        repoURL: https://epam.github.io/edp-helm-charts/stable 
        targetRevision: 1.31.0
        chart: keycloak-operator
        valueFiles: 
          - $values/platform-products/platform-security/applications/edp-keycloak-operator/helm/values.yml

          #- type: manifests
          #  repoURL: https://github.com/wsadza/homelab.git
          #  targetRevision: HEAD
          #  path: platform-products/platform-security/applications/edp-keycloak-operator/manifests

      - type: kustomize 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-products/platform-security/applications/edp-keycloak-operator/kustomize

      - type: helm 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-charts/platform/platform-auth
        #valueFiles: 
        #  - $values/platform-products/platform-security/applications/keycloak/helm/values.yml

  # ------------------
  # keycloak (instance)
  # ------------------
  
  - name: keycloak
    namespace: keycloak 

    enabled: true
    priority: 0

    syncPolicy:
      automated: false

    sources:

      - type: values
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        ref: values

      - type: helm 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-charts/wrappers/app-platform
        valueFiles: 
          - $values/platform-products/platform-security/applications/keycloak/helm/values.yml

      - type: manifests
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-products/platform-security/applications/keycloak/manifests

      - type: kustomize 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-products/platform-security/applications/keycloak/kustomize


  # ------------------
  # openldap (manage clients) 
  # ------------------
  
  - name: openldap
    namespace: openldap 

    enabled: true
    priority: 5

    syncPolicy:
      automated: false

    sources:

      - type: values
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        ref: values

      - type: helm 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-charts/wrappers/app-platform
        valueFiles: 
          - $values/platform-products/platform-security/applications/openldap/helm/values.yml

      - type: helm 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-charts/applications/openldap
        valueFiles: 
          - $values/platform-products/platform-security/applications/openldap/helm/values.yml

      - type: kustomize 
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-products/platform-security/applications/openldap/kustomize
