# ===============================
# 
# ===============================
applications:

  # ------------------
  # keycloak 
  # ------------------

  - name: keycloak 
    namespace: keycloak 

    enabled: true
    priority: 0

    syncPolicy:
      automated: false

    sources:

      - type: values
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        ref: values

      - type: helm
        repoURL: https://helm.runix.net
        targetRevision: 1.62.0 
        chart: pgadmin4
        valueFiles: 
          - $values/platform-products/platform-security/applications/keycloak/helm/values.yml

      - type: manifests
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD 
        path: platform-products/platform-security/applications/keycloak/manifests
