# ===============================
# 
# ===============================
applications:

  # ------------------
  # keycloak-opertator
  # ------------------

  - name: keycloak-operator
    namespace: keycloak 

    enabled: true
    priority: -5

    syncPolicy:
      automated: false

    sources:

      # Keycloak prefers OLM installation method
      - type: manifests
        repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
        targetRevision: 26.6.1
        path: kubernetes/

  # ------------------
  # keycloak
  # ------------------
  
  - name: keycloak
    namespace: keycloak 

    enabled: true
    priority: 0

    syncPolicy:
      automated: false

    sources:

      - type: manifests
        repoURL: https://github.com/wsadza/homelab.git
        targetRevision: HEAD
        path: platform-products/platform-security/applications/keycloak/manifests
