# ===============================================
#    ___             ______                        
#   / _ | ___  ___  / __/ /____  _______ ____ ____ 
#  / __ |/ _ \/ _ \_\ \/ __/ _ \/ __/ _ `/ _ `/ -_)
# /_/ |_/ .__/ .__/___/\__/\___/_/  \_,_/\_, /\__/ 
#      /_/  /_/                         /___/      
# : AppStorage
# ===============================================

# -----------------------------------------------
# @section common parameters
# -----------------------------------------------
#
nameOverride: ""
fullnameOverride: "nextcloud"
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}

# -----------------------------------------------
# @section appStorge parameters
# -----------------------------------------------
#
appStorage:

  # ===============================================
  # @section blob parameters
  # ===============================================
  #
  blob:
    enabled: true

    # ===============================================
    # @subsection secretHelper parameters
    # ===============================================
    #
    secretHelper:
      enabled: true

    # ===============================================
    # @subsection backupHelper parameters
    # ===============================================
    #
    backupHelper:
      enabled: true
      schedule: "0 2 * * *"
    
      sourceBucket: nextcloud
      targetBucket: nextcloud

      backupSourceEndpoint: "http://seaweed-filer.seaweedfs.svc.cluster.local:8333"
      backupSourceSecrets:
        name: "nextcloud-object-store-secret"

      backupTargetEndpoint: "http://192.168.1.10:8333"
      backupTargetSecrets:
        name: "seaweedfs-backup-target-auth"

  # ===============================================
  # @section psql parameters
  # ===============================================
  #
  psql:
    enabled: true
    storage:
      size: 50Gi

    # ===============================================
    # @subsection objectStore parameters
    # ===============================================
    #
    objectStore:
      enabled: true
      destinationPath: "s3://nextcloud/database/"
      endpointURL: "http://seaweed-filer.seaweedfs.svc.cluster.local:8333"

    # ===============================================
    # @subsection backupschedule parameters
    # ===============================================
    #
    backupSchedule:
      enabled: true
