# ===============================================
#    ___             ______                        
#   / _ | ___  ___  / __/ /____  _______ ____ ____ 
#  / __ |/ _ \/ _ \_\ \/ __/ _ \/ __/ _ `/ _ `/ -_)
# /_/ |_/ .__/ .__/___/\__/\___/_/  \_,_/\_, /\__/ 
#      /_/  /_/                         /___/      
# : AppStorage
# ===============================================

# -----------------------------------------------
# @section common parameters
# -----------------------------------------------
#
nameOverride: ""
fullnameOverride: "nextcloud"
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}

# -----------------------------------------------
# @section appStorge parameters
# -----------------------------------------------
#
appStorage:

  # ===============================================
  # @section blob parameters
  # ===============================================
  #
  blob:
    enabled: true

    # ===============================================
    # @subsection secretHelper parameters
    # ===============================================
    #
    secretHelper:
      enabled: true

    # ===============================================
    # @subsection restoreHelper parameters
    # ===============================================
    #
    restoreHelper:
      enabled: true

      # Which backup folder to restore from.
      # This should match the DATE used during backup, for example: 2026-05-26
      restoreDate: "2026-06-05"

      sourceBucket: nextcloud 
      targetBucket: nextcloud

      backupSourceEndpoint: "http://192.168.1.10:8333"
      backupSourceSecrets:
        name: "seaweed-backup-target-auth"

      restoreTargetEndpoint: "http://seaweed-filer.seaweedfs.svc.cluster.local:8333"
      restoreTargetSecrets:
        name: "nextcloud-object-store-secret"

      # Safety options
      dryRun: false
      deleteExtraneous: false

    # ===============================================
    # @subsection backupHelper parameters
    # ===============================================
    #
    backupHelper:
      enabled: true
      schedule: "0 2 * * *"
    
      sourceBucket: nextcloud
      targetBucket: nextcloud

      backupSourceEndpoint: "http://seaweed-filer.seaweedfs.svc.cluster.local:8333"
      backupSourceSecrets:
        name: "nextcloud-object-store-secret"

      backupTargetEndpoint: "http://192.168.1.10:8333"
      backupTargetSecrets:
        name: "seaweed-backup-target-auth"

  # ===============================================
  # @section psql parameters
  # ===============================================
  #
  psql:
    enabled: true
    storage:
      size: 50Gi
    # ===============================================
    # @subsection bootstrap parameters
    # ===============================================
    #
    # @param appStorage.psql.bootstrap.mode               : Bootstrap mode for the cluster; allowed values are initdb or recovery
    # @param appStorage.psql.bootstrap.initdb.database    : Initial database name; defaults to <fullname>
    # @param appStorage.psql.bootstrap.initdb.owner       : Initial database owner; defaults to <fullname>
    # @param appStorage.psql.bootstrap.initdb.secret.name : Secret containing database owner credentials; defaults to <fullname>-database-secret
    # @param appStorage.psql.bootstrap.recovery.source    : External cluster source name used when bootstrap.mode is recovery
    #
    bootstrap:
      mode: recovery

    # ===============================================
    # @subsection backup parameters
    # ===============================================
    #
    # @param appStorage.psql.backup.generation : Active backup/WAL archive generation name; used to compute serverName when not overridden
    # @param appStorage.psql.backup.serverName : Override active backup/WAL archive serverName; defaults to <fullname>-<generation>
    #
    backup:
      generation: "2026-06-05"
      serverName: ""

    # ===============================================
    # @subsection recovery parameters
    # ===============================================
    #
    # @param appStorage.psql.recovery.sourceGeneration : Source backup/WAL archive generation used for recovery
    # @param appStorage.psql.recovery.sourceServerName : Override recovery source serverName; defaults to <fullname>-<sourceGeneration>
    #
    recovery:
      sourceGeneration: initial
      sourceServerName: ""

    # ===============================================
    # @subsection objectStore parameters
    # ===============================================
    #
    objectStore:
      enabled: true
      destinationPath: "s3://nextcloud/database/"
      endpointURL: "http://seaweed-filer.seaweedfs.svc.cluster.local:8333"

    # ===============================================
    # @subsection backupschedule parameters
    # ===============================================
    #
    backupSchedule:
      enabled: true
