# ===============================================
# Author: Igor Sadza
# Purpose: Manage Keycloak instance
# ===============================================

# -----------------------------------------------
# @section common parameters
# -----------------------------------------------
#
# @param nameOverride      : String to partially override common.names.name
# @param fullnameOverride  : String to fully override common.names.fullname
# @param namespaceOverride : String to fully override common.names.namespace
# @param commonLabels      : Labels to add to all deployed objects
# @param commonAnnotations : Annotations to add to all deployed objects
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}

# ===============================================
# : platformAuth (wrapper)
# ===============================================
#
# @param platformAuth : Platform authentication wrapper configuration

platformAuth:

  # ===============================================
  # @section Keycloak parameters
  # ===============================================
  #
  # @param platformAuth.keycloak.enabled : Enable Keycloak resource management
  keycloak:
    enabled: false

    # -----------------------------------------------
    # @subsection endpoint parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.endpoint.url    : Keycloak service URL
    # @param platformAuth.keycloak.endpoint.secret : Secret containing Keycloak admin credentials
    endpoint:
      url: ""
      secret: ""

    # -----------------------------------------------
    # @subsection realm parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.realm.name : Keycloak realm name
    realm:
      name: "" 

    # -----------------------------------------------
    # @subsection realmComponent parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.realmComponents                : List of Keycloak realm components
    # @param platformAuth.keycloak.realmComponents[].name         : Realm component name
    # @param platformAuth.keycloak.realmComponents[].enabled      : Enable realm component
    # @param platformAuth.keycloak.realmComponents[].providerId   : Keycloak provider ID
    # @param platformAuth.keycloak.realmComponents[].providerType : Keycloak provider type
    # @param platformAuth.keycloak.realmComponents[].config       : Realm component provider configuration
    realmComponents: []

    # -----------------------------------------------
    # @subsection groups parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.groups               : List of Keycloak groups
    # @param platformAuth.keycloak.groups[].name        : Kubernetes resource name for the group
    # @param platformAuth.keycloak.groups[].enabled     : Enable group management
    # @param platformAuth.keycloak.groups[].groupName   : Keycloak group name
    # @param platformAuth.keycloak.groups[].namespace   : Namespace for group resource
    # @param platformAuth.keycloak.groups[].labels      : Labels for group resource
    # @param platformAuth.keycloak.groups[].annotations : Annotations for group resource
    groups: []

    # -----------------------------------------------
    # @subsection clientScopes parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.clientScopes                            : List of Keycloak client scopes
    # @param platformAuth.keycloak.clientScopes[].name                     : Client scope name
    # @param platformAuth.keycloak.clientScopes[].enabled                  : Enable client scope
    # @param platformAuth.keycloak.clientScopes[].protocol                 : Client scope protocol
    # @param platformAuth.keycloak.clientScopes[].protocolMappers          : List of protocol mappers
    # @param platformAuth.keycloak.clientScopes[].protocolMappers[].name   : Protocol mapper name
    # @param platformAuth.keycloak.clientScopes[].protocolMappers[].config : Protocol mapper configuration
    clientScopes: []


    # -----------------------------------------------
    # @subsection userDefaults parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.userDefaults                        : Default values applied to Keycloak users
    # @param platformAuth.keycloak.userDefaults.enabled                : Default user enabled state
    # @param platformAuth.keycloak.userDefaults.emailVerified          : Default email verification state
    # @param platformAuth.keycloak.userDefaults.passwordSecret.key     : Default Secret key containing user password
    # @param platformAuth.keycloak.userDefaults.requiredUserActions    : Default required Keycloak user actions
    # @param platformAuth.keycloak.userDefaults.roles                  : Default roles assigned to users
    # @param platformAuth.keycloak.userDefaults.groups                 : Default groups assigned to users
    # @param platformAuth.keycloak.userDefaults.reconciliationStrategy : Default user reconciliation strategy
    # @param platformAuth.keycloak.userDefaults.keepResource           : Default keep-resource behavior after Helm release deletion
    userDefaults:
      enabled: true
      emailVerified: false
      passwordSecret:
        key: password
      requiredUserActions: []
      roles: []
      groups: []
      reconciliationStrategy: full
      keepResource: true

    # -----------------------------------------------
    # @subsection users parameters
    # -----------------------------------------------
    #
    # @param platformAuth.keycloak.users                          : List of Keycloak users
    # @param platformAuth.keycloak.users[].username               : Username
    # @param platformAuth.keycloak.users[].enabled                : Enable user management
    # @param platformAuth.keycloak.users[].firstName              : User first name
    # @param platformAuth.keycloak.users[].lastName               : User last name
    # @param platformAuth.keycloak.users[].email                  : User email address
    # @param platformAuth.keycloak.users[].emailVerified          : Mark user email as verified
    # @param platformAuth.keycloak.users[].passwordSecret.name    : Secret name containing user password
    # @param platformAuth.keycloak.users[].passwordSecret.key     : Secret key containing user password
    # @param platformAuth.keycloak.users[].requiredUserActions    : Required Keycloak user actions
    # @param platformAuth.keycloak.users[].roles                  : Roles assigned to the user
    # @param platformAuth.keycloak.users[].groups                 : Groups assigned to the user
    # @param platformAuth.keycloak.users[].reconciliationStrategy : User reconciliation strategy
    # @param platformAuth.keycloak.users[].keepResource           : Keep resource after Helm release deletion
    users: []
