apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret 
  namespace: keycloak 
type: kubernetes.io/basic-auth
stringData:
  username: keycloak
  password: admin 
---
kind: Secret
metadata:
  name: keycloak-secret 
  namespace: keycloak 
type: kubernetes.io/basic-auth
stringData:
  username: admin 
  password: admin
