apiVersion: v1
kind: Secret
metadata:
    name: igor-sadza-secret
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JmKszodcR3jh,iv:TSxNtjoN8pnriu0DMTvDpUyGBj5EFu06fxIDktMoUfA=,tag:uBWK//9S88s8auwya1b5Aw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTGNqVU5TREJCK3NKbEZC
            empoTm1mbzN6VnA1a0JsU0ZyakFwUjZVamdNCnVvRkV5MkVobXc5dzM0NWFvRW9x
            TmlwUjZWUFNXcGZSODFzaXJzSEZNb3MKLS0tIGVqV0JiS1oweHlmRVBndkExcDZv
            b1ViS21WV3hONHBGcGVQalF5TE84bjQK9M89mtEBZdeHjlHA/KtByWKBn1ePIIaE
            mDb3OMPvTJTUd2DFQTPssXnpjD3vuEC/MhDnNfQ+vjtztBTc/8PQcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T10:15:39Z"
    mac: ENC[AES256_GCM,data:oPzTvF/a2E1VoP6ij6/IAMZi4GT9Sdoklnhg0A3vFnIexea04y2vmkTrNKltUM8J31lx2e4Le+Si2zP0gvZutT+j4YSRPADclehbqPW8mGzByurRSAN+uK1sVsHhtFJuiD242R75ll2FobjdFNIii/oz+wSRgqmMzFzloNgXKVw=,iv:2JVDNWFO360FXvhHf9gr9/B6dkscYbyrz2yELcrhCs0=,tag:0wOKBdlzapnZpHKyqabMeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
