# ===============================
# 
# ===============================
applications:

  # ------------------
  # Podinfo
  # ------------------

    - name: podinfo
      chartName: podinfo
      enabled: false
      #chartPath: 
      targetRevision: 6.9.1
      repoURL: https://stefanprodan.github.io/podinfo
      manifests: true
      chartValues: true
      namespace: podinfo 
      priority: 0
