apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: seaweedfs
type: kubernetes.io/basic-auth
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:u11EkwSRSAUjVaF+r1D8o8ZNSvzqFMBv2dx9vJdjpr6gvLy1wqOCQ6s3EIClJjgTOo8btBUgJobYQ/8tmn4YnQSjKss/SHefK+2QZThai9rHeJKZtK4jK8eKxfmR4N7iMOuJHdrf7rFLUcPj7XeKJSiZm+BnY6aurRF7syAakBghVtoA+5Tv+HtJ0vbHd8CWZNPW1R8I3mvwKHWzMt2TSMqVoNubie/YyDjhLAcEWEDXD6miKh44AhtUum8D04afvVxc8uBCAlRSd0g1RQdki/4ctiAjffx5RpaZPKgbpxTfROcYS1fAHHcg/3urzf7x2YXP73WufuINlXFZ0iXpjitbV91JZ9hlTKKTcYdLuqCorG0VnH59YrRjQLeoOBqXC8ttXmew/cizP4c=,iv:Mp8E30gOBCUFsdOo7b1yu8ueFuqilV/C/ggADXed8nA=,tag:MoJLaqX+8wITGT2QFVC4uw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDJaVWxKeG5rYUx5YVUw
            ekNSbXdraEUvaXEwT1ZlSmluNWZoK2ZiMTBrCnBVUTF1M1VFa2YzbTRaNnhqSlFK
            ODBUWjRRS0tjbHZWMG1ydHZzVGh3ZUEKLS0tIEk0bUpBNHRuOXhncDR1VjcySE1p
            U3VhUjB5b2RQNGNVWlZFYU8ySXZydk0KHhnhrqMMywg509LGZxzqeToAoqu6uzN+
            iaauMXZcg/4UvPXsPbl3neqkThaZTmyD+VBpW1ao4EiyQBj5W6tVAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:25:03Z"
    mac: ENC[AES256_GCM,data:FoIwkNNaupZwpN7tz8RhP9agUHU3xfJv1ROS8BG6LHZwHZrQ2qf7oS56Ln6LsSN2QapS88//BK1kIFlxG5LyLITYq7OQuU78aRi6zGSf3wFJT/q5G6jXPxAaYg2iqvZj7YvLzSbmKoTDWz2R610baqyD8xjB9dH+ut/QoSrckrg=,iv:InaHFp//C6eCa7mAD3nhJWbI7BjlMC98K8ko4QOd/Ik=,tag:NfvmOeDZA3NZJDq1Hbo9pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
