apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: seaweedfs
type: kubernetes.io/basic-auth
stringData:
    seaweedfs_s3_config:
        identities:
            - name: ENC[AES256_GCM,data:LDrMTi0qjQuh,iv:1b3+oMV5wuIInSEB1laX3Q2ArXSKe8vznQDmAceTIv8=,tag:VWHQP7dReO/RkTuzVubcfg==,type:str]
              credentials:
                - accessKey: ENC[AES256_GCM,data:kx8z87Pd6rpe,iv:OBGVXbSHthBfjhBv84KafXmxJzpSMyw1uLkE7z+Nex8=,tag:AzK2XyvJAe6qw+ZuE920Cg==,type:str]
                  secretKey: ENC[AES256_GCM,data:/F9Vb/4iQZ8T,iv:Pfffu6MIhfEyfnZ5aCK9e7VB0qPd6wMpsqv6OTTdnWw=,tag:fQMYZfAwEZ8Ns8u8129c/A==,type:str]
              actions:
                - ENC[AES256_GCM,data:f71yj6o=,iv:CFj6p8jjktsmN7P/fItcyFzvwRt4UQzaph68//O0yxc=,tag:OxVq7t66s6HbeCppVUB83g==,type:str]
                - ENC[AES256_GCM,data:nqtF+g==,iv:s9rMtEJRt1J6l0yUUI09d87hSe3hR/4j3glbY6Kcu1Y=,tag:yiw16fWMfaWkLj9BVjvaqQ==,type:str]
                - ENC[AES256_GCM,data:9cJCV+s=,iv:SdYqaeU+wyvviuRnMW3I2NvauFJ2PCyN9IMPlg/OBpk=,tag:E/lCk5gXyNtKj9alKTJXXg==,type:str]
                - ENC[AES256_GCM,data:g8zoTA==,iv:B59PNs/re2uyVpkjGFHKnCrbZPp0osl0LxnUZE5ZTG4=,tag:EKCJtc7zJG1wMDxaOJxA6Q==,type:str]
                - ENC[AES256_GCM,data:xeRIOiVUYw==,iv:gKQdDkWYlWMEuh7Yb6O5chhlwq7N5hF9CXA3LcsdQLY=,tag:XZycWFg/lEpErhD3Wc22og==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdy9FbHQ4OVkyeFkyeEp4
            dWhIcXpxZXlnYU9LbXYwSTZ6eElCVkFkOWhNClZUSnkzK2FlVTlCOW9rQ3R6cEhJ
            WlovUkFPYTJkbHRzcGcwWC9qL2JlbDQKLS0tIFl2N1VSZ1plazgzZkErTHYvTDFV
            a0Fqb244TUhTbjJ6S2EzME1NNTlSNTQKgNCyxsIzYAQWGKP0u7Wn/DHyXlpHTeZg
            VGfwEcTVUBsgjGkuBFIvoBmqF+yw8doFeKRhFszoxrGPC6z3B6uoeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:24:00Z"
    mac: ENC[AES256_GCM,data:P34zEBIct0dsChEgMDpD6G4d4xOzKUdqSkBGOCLsI7i8m+veqo6S2ralzdZtsxnjhpz/dKG1Fsb2V3Nhy2mcXNZ6wjys2+K9i/gVk7jebFGEWpaoDZ/SLMiK3E3CLWQ31r5NUDHjZENrrLklnn754MixR9fa49BP5KNSqeZ+cZI=,iv:cA1cb74FfhNXuiOpJVrVXLSJwKJ7sk3epQgcYtGmWu8=,tag:Gcekv5bWqfbufTeHIelOeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
