apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: seaseedfs
type: kubernetes.io/basic-auth
stringData:
    seaweedfs_s3_config:
        identities:
            - name: ENC[AES256_GCM,data:nnI79WV9kI6C,iv:47KRnXIUC57/tMf4RHrDX1WyC2ltkMJpyWu1l+kFqPg=,tag:l4FfDELG08QQf3IzR/zAJg==,type:str]
              credentials:
                - accessKey: ENC[AES256_GCM,data:8evi33aEMwnx,iv:DbBh82+GuZEvG8Kn/LE4sh8UWWQD4ftUUVSMnJrCbh0=,tag:+JnJufA4VBuX7HTxQxB4pw==,type:str]
                  secretKey: ENC[AES256_GCM,data:qaZaXYvCM+jC,iv:aOLaiasI4xXPpQLDZCIFcgFIBz611BiZ9wqHW0XGkcQ=,tag:pDYx0Cvd985oQT8d9zQ74A==,type:str]
              actions:
                - ENC[AES256_GCM,data:sUCxquw=,iv:WvzCaNeOezmBpej+5x3Flf41Vz9J5emdAQ9PLVh0ujM=,tag:wyJ94JKsi1k+1Sgn0tdUHg==,type:str]
                - ENC[AES256_GCM,data:2gEcsg==,iv:KE+ZCQYB/p7u3d4ewdwoRREqrD6kVh3ralkDJhhjWdU=,tag:TYf8ZxHjef2kkqMQNEC1RA==,type:str]
                - ENC[AES256_GCM,data:n4cCvXI=,iv:t8v1I2O1bCIuAKne878sNqCoit/DeJcwwKjgZLcr4bg=,tag:Dc67c4tlgccdpYRybnmA3g==,type:str]
                - ENC[AES256_GCM,data:kKkqYQ==,iv:3YSYnQfhV0EE46OFOpfmzUNRRvmGB0ypwm+Gof4ADH4=,tag:4uIPYUz+9Ml7D5x7KxOwaA==,type:str]
                - ENC[AES256_GCM,data:G2LK6SFIsg==,iv:3plhSYfZDTBdKVaigMEghIKscRVxwL1EYtIAFsGtuts=,tag:IZhRCFiEng7c/0o/rJbiDA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreTBSM1NFR0JGcFc0Q0Nx
            RFVEU3VDVjdwNWY1dlNJcGNzYUNWSnFmOUJZCnhsZlRvMExFTFdSVFNOSm5hTVdY
            Uno3YVdjZFJTZFhTV0Z6aU5QODBwSVEKLS0tIDhDMUszNi9ETXc2UmVDb1NlaUFr
            eFZMbVArSWdQM2dFeGdLbEJYV3E0YXcKt7vwJBN5x+wgxrcdcZOQ7aeAQbK8N+2M
            Sv8DHFaiQWxWRI6/eeU1Jz34V6XRCxEwCuVeR+lttKjx2ptRFouLNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T23:14:05Z"
    mac: ENC[AES256_GCM,data:yczydTpjG2Qr9YJe1gIePy067ts/+wkhFe2fXoxkcG5nwOXlXZ8OzTgrIwGhEQURu/j3BAUCuDwfE7JivZTgCbylblQ6F5yHa2H9VEauS7IXt5XsgbM8om5otbqIQgHNKEWhEdVoaOlfVYaalXEc+eyfrPKde9IVDHBSW5nusAM=,iv:RXBoS1z3tYAY1PztNYxpqyIIBP3NvRVdAAC8xmQY+aI=,tag:ZSf6RK1ddysHIjjs1BRwbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
