apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh
type: Opaque
stringData:
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:ZefcKI52VMT1XYGwilPMuA==,iv:aj0zrg4sDJ3gZMG7Uvzjs4OWX6+Gs3SDbmuWXbM85Y8=,tag:WAPAsr3Gl617b658kxawsA==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:snVsgfHbPEuxGZmApXGVRmjbtm8ECE2vfusf8KPKIm4=,iv:c0xGXrcC58V9s5GSf3EW0DsBFciI4xbXMI4G1nCEAPk=,tag:tUsPWaa+YXovmR6GImJyxg==,type:str]
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:RHTWhsKF3Ezt0yJpXf2+P8ecVLdoiMVeiR9PAfxxWfE=,iv:1mJAs39HPf7n3zzrwdYnaPoWtbEWGNkSDkQZK9sTwPQ=,tag:90CRAqf+BEhxxa0DYqv/jA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSXp2elVZRFkwVzhkRmJw
            aExZYUxkaW01SjBPVHF0b3FRcUkrWEdIMnprCk0wVHpBSWJ4a0wyQS8yeVdXZXN6
            MkdQUC9XbjltWE0wYWZibUIvMmpWQzQKLS0tIDNuaFlIQW1laXEyaGp0ZnJ3L3dC
            YXk4MHdEaDZEdWdTNnk4Z3pROHN2dmsKy9Ea1Fpiw0ET3F3dd04TjGMMCbVAj4ed
            BPFjVtwuqYnqoz5i6iIINv768Th/Iq5x9tZe4qp1LIOa/wWhHdyJiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:26:25Z"
    mac: ENC[AES256_GCM,data:pc+ZgsSDy4WUTnPpLzTuz+U3f33PfhrmFgZNK62pHiep0hE5ROzgx30v0ZWjHVIYq7PldlpP+VtUOofbt+wMe/zQM2zPAlf7zqxBogVIxZxKbSzWAPgM5NvRoFn7vDsNresVTZQclQeF8FiRBXYd/EfpS25q/UKQBq93fgEQwps=,iv:lBBlH1quknXG7EVXmCQFKGDqJ957UPFfEmGusgHWcBU=,tag:rECx8lU35WNZyEdFYfA78Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
