# ===============================
# Product: Infra-Core
# Author:  Igor Sadza
# Purpose: Core applications
# ===============================
applications:

  # ------------------
  # CertManager 
  # ------------------

    - name: cert-manager
      enabled: true

  # ------------------
  # EnvoyGateway 
  # ------------------

    - name: envoy-gateway
      enabled: true 

  # ------------------
  # External-DNS 
  # ------------------

    - name: external-dns
      enabled: true 

  # ------------------
  # External-Secret
  # ------------------

    - name: external-secrets
      enabled: true
