# ===============================
# Product: Infra-Core
# Author:  Igor Sadza
# Purpose: Core applications
# ===============================
applications:

  # ------------------
  # CertManager 
  # ------------------

    - name: cert-manager
      enabled: true

      namespace:
        name: cert-manager
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # EnvoyGateway 
  # ------------------

    - name: envoy-gateway
      enabled: true 

      namespace:
        name: envoy-gateway-system
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # External-DNS 
  # ------------------

    - name: external-dns
      enabled: true 

      namespace:
        name: external-dns
        autocreate: "true"

      syncPolicy:
        automated: true

  # ------------------
  # External-Secret
  # ------------------

    - name: external-secrets
      enabled: true

      namespace:
        name: external-secrets
        autocreate: "true"

      syncPolicy:
        automated: false
        syncOptions:
          - ServerSideApply=true

  # ------------------
  # Platform-Secrets 
  # ------------------

    - name: platform-secrets 
      enabled: true

      namespace:
        name: external-secrets
        autocreate: "true"

      syncPolicy:
        automated: false
        syncOptions:
          - ServerSideApply=true
