apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: external-secrets
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EIFBD4vB,iv:m7uUror/I/AkccUV6FmAJzsZPBXz7sVZpaNLzdZwNMI=,tag:XcJKQyMITyEheHMVDij5dg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hjAjt/8WNg3+,iv:2OaqNiNqFrMad0FlcJxOCTk/c5DhuxWP97L7Y4nHwoY=,tag:gPNeF2DgH5afi95D1X1wGQ==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQVNVOWpla2UxbDVZV1oy
            T1k2WG11cXZrQmZrWGdtMUFsTGtiWm9UMDBBClNaT0xyWDgva2Q0bFh4R2hKemFV
            ZFp3Z1RMNHl0Wk83MWllMXlFcTFyeUUKLS0tIDcxYzA5Y0dPaGhnYUZ2Qk4yS0xW
            UG1ZTVVWKzAxRFhoQ25nQ0MvMERiTkkKTCO0cynn6h6MR2Uzw7zHPBzMqbRdZ60V
            XMcho+U3xFayLSb+mRpHWQ3Og2x6LKcJ3Hd4vyanQ1cy6w/IxSh01A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T21:40:42Z"
    mac: ENC[AES256_GCM,data:t9yzk+jV7A0nr71fbVbp0+EDEMVcxN1q8dRBOFwnyD3rU5NfVDa+VDKSeFKxYjTcm08RytVKv/ypPCn4M0g1yIscj80ZEc9+sy7pNPpi8Fcc7tXLpdUjknveaz/tqEdupyi/ywapkEimUUUnxJlXSZNHR6JNvXMpuIBo3ToaXgg=,iv:gaiWfMu6CtNbvp862VnoY0+CBsg/n7iOoSMwueHR298=,tag:jpUbIYnRSWkBbv2qY70eaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
