apiVersion: v1
kind: Secret
metadata:
    name: seaweed-backup-secret
    namespace: external-secrets
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:YVsgt+O8,iv:qstAAy3xqjn675yZAYvPEYhnhGyd9FbqQ5H4zJ5QcHM=,tag:nkoDp0F4VJSILJDMgI2jeA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:mhHNcagVpRlc,iv:YcYMJ8LygTiTOto3lZcAUdtPOsibftP0MEJ/nbPsj1M=,tag:CY+H1qebvBsXQs4zNTeDpg==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZWozSlBZNEw5LzJ2QjZV
            SjJYTnJyY2VQV05tZVFZTXBzVUdTRm05N0JVCnNMUlVSTmVPQ1UvWDVWOCs3OGxI
            UGRQMWR1VFdEWXlPVXdzaDloU0lNRncKLS0tIDlHL2ZTcHhoVENZMlh2QW4yamlU
            SS96NTE0ZEk4eDJoV1o4a2FDdGl1amsKgEmP0V+iIM2Su6Z+G+uYswehyvL8p/9W
            K3QjFewkg+qqQ/xbi9ilCRCxBJJ1WhoAPdfJV64O9txM5N4CSoze7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T08:12:01Z"
    mac: ENC[AES256_GCM,data:Zle/XRgBCcxTcKaGQylaAZxZwfJLnIcjunufFz7gPw9XB/wR2qUIkDvC/qUeScIgkiv0ZXEHZP88QTWJEiK9tYKOxjjweAQd4qC0K7WZKqPuXcZ3DlVDZ0iLf4kq62kXP3O+a3aCJTK0kDZsXpWrH6ekPi+Rtnfk3vtpoihJAIU=,iv:gGTiVU3Bu3F0nBNPkzTyJbzc27xOqxkKMQVlyJuygJE=,tag:BLxJit9X8tGkF0vnU2sE9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
