apiVersion: v1
kind: Secret
metadata:
    name: seaweed-backup-target-auth
    namespace: external-secrets
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:MGnaj63v,iv:m/k9Jt9YcpuHgnv4VZnJwM3eGqKI+vVUA2kORngXLvU=,tag:Z1x+ZU09sE6nvnNHa3YVBg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:diMPGgqydw7U,iv:XNNWSAtKm7LvYKai1UswYaBefS+qR4TuEvCUET7W9To=,tag:KMqBLYNIUSWHdtvEm34XxQ==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT1FDbWo0VlhzSGlCaFlM
            a040YnROTVpteFJ6b1JWd0lxb01zelVwSjNRClRpZkZLUC8zR1EySDVZVWQvRlUv
            ZTVpRmZKdlpYVnNrUWhEN0haZEU5SmsKLS0tIGM5aFMvNEFnQmxYQnJhU1Z3dE9G
            ODd5RDJJaXhUZkZRNVkvbUx4ek0wbnMKGbWLMVCxS0Ku4y3q2k0SM7YuJcnpT2j0
            soLY40PFs9a8mLeHbwtJXeQ1L3OSx38FI9+ZqDPaLgwcxlxeZFAlrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T09:11:11Z"
    mac: ENC[AES256_GCM,data:920xDO6jDT5hEO1NGVBiqSwJmV2KFE0IoJp3MvvTdxxRfrE/6HROpWRCFd1xxvv+t4CTrSWUbcHFLKPaFBFANItaKNHTXKH6voHCL2zHZSjPGMbaRvLvWjB2mrJU0kI74TdWLPFRTXX/ZUvS8JzRY+BMHxYwxn1F5PG8ZCVGu4Y=,iv:5DpBJFEi7GwW+mHBqsGefWCMWTe3mDispqmW5QjMhaM=,tag:7cZsMDp5eFd03/KJ2Tj+ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
