{{- if and .Values.appAuth.envoyGateway.oidc.enabled .Values.appAuth.keycloak.enabled }}
{{- $root := . }}
{{- $oidc := .Values.appAuth.envoyGateway.oidc }}
{{- $client := .Values.appAuth.keycloak.client }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ default (printf "%s-oidc" (include "common.names.fullname" $root)) $oidc.name }}
  namespace: {{ default (include "common.names.namespace" $root) $oidc.namespace }}
  {{- with $oidc.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $oidc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    {{- range $oidc.targetRefs }}
    - group: {{ default "gateway.networking.k8s.io" .group | quote }}
      kind: {{ .kind | quote }}
      name: {{ .name | quote }}
      {{- if .namespace }}
      namespace: {{ .namespace | quote }}
      {{- end }}
    {{- end }}
  oidc:
    provider:
      issuer: {{ $oidc.issuer | quote }}
    clientID: {{ $oidc.clientId | quote }}
    clientSecret:
      name: {{ $oidc.clientSecret.name | quote }}
    redirectURL: {{ $oidc.redirectURL | quote }}
    logoutPath: {{ $oidc.logoutPath | quote }}
    {{- with $oidc.scopes }}
    scopes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $oidc.forwardAccessToken }}
    forwardAccessToken: {{ . }}
    {{- end }}
{{- end }}
