{{- if and .Values.appAuth.keycloak.enabled .Values.appAuth.keycloak.client.enabled .Values.appAuth.keycloak.client.clientSecret.generate }}
{{- $baseName := default (include "common.names.fullname" .) .Values.appAuth.keycloak.client.clientSecret.name }}
{{- $generatorName := default (include "common.names.fullname" .) .Values.appAuth.keycloak.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-client-secret" $baseName }}
  namespace: {{ default (include "common.names.namespace" .) .Values.appAuth.keycloak.namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: {{ printf "%s-keycloak-client-secret" $baseName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ .Values.appAuth.keycloak.client.clientSecret.key }}: '{{ `{{ .password }}` }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ printf "%s-secret-generator" $generatorName }}
{{- end }}
