{{- if and .Values.appAuth.keycloak.enabled .Values.appAuth.keycloak.client.enabled }}
{{- $root := . }}
{{- with .Values.appAuth.keycloak.client }}
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: {{ default (include "common.names.fullname" $root) .name }}
  namespace: {{ default (include "common.names.namespace" $root) .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $root.Values.appAuth.keycloak.realmRef }}
  realmRef:
    name: {{ .name | quote }}
    kind: {{ .kind | quote }}
  {{- end }}
  clientId: {{ .clientId | quote }}
  public: {{ .public }}
  directAccess: {{ .directAccess }}
  advancedProtocolMappers: {{ .advancedProtocolMappers }}
  secret: {{ printf "$%s:%s" .clientSecret.name .clientSecret.key | quote }}
  webUrl: {{ .webUrl | quote }}
  adminUrl: {{ .adminUrl | quote }}
  homeUrl: {{ .homeUrl | quote }}
  {{- with .defaultClientScopes }}
  defaultClientScopes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .redirectUris }}
  redirectUris:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
