{{- if and .Values.appAuth.keycloak.enabled .Values.appAuth.keycloak.client.enabled .Values.appAuth.keycloak.client.clientSecret.generate }}
{{- $baseName := default (include "common.names.fullname" .) .Values.appAuth.keycloak.name }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ printf "%s-secret-generator" $baseName }}
  namespace: {{ default (include "common.names.namespace" .) .Values.appAuth.keycloak.namespace }}
spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
  encoding: raw
{{- end }}
