#apiVersion: v1
#data:
#  client-secret: TDhaOFZQNElvREVmeVNtWnZmRHEzZUoySFgzWHJkdnpBZ2czRTdocDNVNlVTSDJx
#kind: Secret
#metadata:
#  name: podinfo-keycloak-client-secret
#  namespace: podinfo 
#type: Opaque
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: john-doe
  namespace: keycloak 
spec:
  realmRef:
    name: keycloak-realm          # KeycloakRealm CR name, not necessarily realmName
    kind: KeycloakRealm
  username: john.doe
  firstName: John
  lastName: Doe
  email: john.doe@example.com
  emailVerified: true
  enabled: true

  passwordSecret:
    name: john-doe-password
    key: password

  requiredUserActions:
    - UPDATE_PASSWORD

  roles:
    - offline_access

  groups:
    - PodInfoDevelopers

  reconciliationStrategy: full
  keepResource: true

---
apiVersion: v1
data:
  password: YWRtaW4K
kind: Secret
metadata:
  name: john-doe-password 
  namespace: keycloak
type: Opaque
