apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh
type: Opaque
stringData:
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:SRnikFi2ynotHaxRqkaBaQ==,iv:7hWMe00lKr4Y9zpYjdhkgNLripeuP3ePXN3/91zH/Uw=,tag:BpKjVyewRxfCIxaGvWHxZw==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:g6DqX7T9TcT7GoZSnmpoAIte1d7Hvi62TDjkcghcvF8=,iv:c109MsKFjEkco/bbcu9iaewuq1X+PtzlxWWWnjI9Bwg=,tag:t4bJv/s2t4kkAMtl8C3eNA==,type:str]
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:KI5Ax1ybMZBFE/8ipd43BEktZKlRRYFDf17C1q4y3x0=,iv:Nl8cL/zyv0wJCaLSGml3P5xo4KXB2RZ/sAM5RD8nkuc=,tag:oOq/jor8ewCSnapHi8pJkg==,type:str]
sops:
    age:
        - recipient: age15auqe06w4jw4awxgcmsxa6fxg9nve8jnxdemxeuq0y2pepmx3uus7umr0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MldJY2xwYVRKOWZLbDRQ
            SnBRMkNhL241SnN6K0VrKzhmNkpvcDRsVW1VCnBheGJjenZMeDRhS3c4cjFrQytW
            elNrRFhxK3FhOW5ZUXNpaFVUU04vL2sKLS0tIE43bk5mOE9Xeko5dUVNMXo2bjBK
            cnNTZEJrWUtqUFA4dmtYcjRqQWhwRU0Kmmdf8hHoVOQvDYZ1Fhkt0DmTK7Ls6QbC
            0HTxfqopG69FU3y7QgeUAyphhd59emYl24Qwymkx3U0dCX3JTcyITg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T11:48:04Z"
    mac: ENC[AES256_GCM,data:htucrf55suOW1xEzldKkFoyxnqGB+arsZvrbvOPvTqrDBmnIEe3epSPERFEr8JugpaMJECsm2J9+dLnooY84JqhGBptTxZvwdau9Q5ZOq4hpzPdOD1wl1xuQe9C0ApmsGvd02YaS/wzAkAnq748Lw8IjH/SEumRCQt8gJOrMAAc=,iv:Edyndro33adQOd9Me04ETpB0gAcwdprISktJ5HNX5ok=,tag:RJWASD0CS509jJO1YEZozQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
