apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh
    namespace: external-dns
type: Opaque
stringData:
    applicationKey: ENC[AES256_GCM,data:Y4GU6EA/xWJnCIfImTLxOg==,iv:l1Iccvu5llO1UFO0c9T7hul7yxwd6vgiyAaFEjDqles=,tag:aVrnADms8cDvuAg5VCogHg==,type:str]
    applicationSecret: ENC[AES256_GCM,data:O2gghUYWlUTT8HFQk3y7UbL144pF6zcX5LDQ4IHWTH8=,iv:eyMXff8Bydu8N/j92dPqpvsZJoGNxY1Tn30y/Tz1JkU=,tag:NONwdHRvBnS5+b49X5S/Cw==,type:str]
    consumerKey: ENC[AES256_GCM,data:yszmU9MkLVIemiFFip+zTgbAxC7Bh64gmTE6C6COI1E=,iv:j0gmSj59ZpKveA6xhM1HlYc7eWlPf4aWVLlbvwiEP38=,tag:sFC79Hp11xUG8A8x5YQqgQ==,type:str]
sops:
    age:
        - recipient: age15auqe06w4jw4awxgcmsxa6fxg9nve8jnxdemxeuq0y2pepmx3uus7umr0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q3B5dkhlWk1lMHV3NHNU
            K3Q3dytIY3MrcnYrZElqUWhqdzEzeGE3SmxzCmlpSXBjWitiMFA4U00vLytIZWlJ
            VHJaUlg0L2tYL2pHYVg2MjBGblk3SDQKLS0tIDVpaVg3QWorMEJkYjJBUWJQQUNK
            dGl4RXBsR0oxUFdCNmJDak9xN0s2U0kKRu2N43AHJqoDEtLr4mYF1TJNo3yj3DWa
            op8zSOEeppn7hncGNhLkBpnTgqfDaGK8NgqSiiaYkZJcLZIsmierhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T09:20:28Z"
    mac: ENC[AES256_GCM,data:+WKPv3H0eCZaZgoirxy6bLjf30sEEzdJt8wg6baqy8N5K4BbIFnKJDdRnzZgesw3R/Pk2YIWhQfce46C79S0TX+Mwdj8ZCGAivYcbur+BCPBQ9NkR3Z8pjPgZzbpoGb8CBIxR8KKtj4NcpI2xgy3xkjQ8dHey5f9ltA+kYg7KSo=,iv:M8sUPL21vRrbBoMNlt+OHUzMRiKRIWB+9744fIHOReg=,tag:fxUXPrAuIYePL+ixTAgpBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
