apiVersion: v1
kind: Secret
metadata:
    name: external-dns-ovh
type: Opaque
stringData:
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:rRCbCW6jItQFHoq1K1AiQQ==,iv:ULfRGwwrL3hcXxelLaUNuLp9Zl++l3RT9jtx+uTEJ0I=,tag:9TWkrQrR4Fh4L4Fb2qe19g==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:0pJxrzQqDlQr9/POklUhKf6Lx3hTM4EmK7Zqdbik4m8=,iv:yHMNX2xZDGxsZAhUKNudjEj56CDI14kYrSBE8CROOfA=,tag:CyLJ2WVs3gU2Yvd/GgahMA==,type:str]
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:oW9M1tWenLVUpZ7vn0M/puJhD0HZI9cUWXBgoVBdjbA=,iv:appzb5Kvr4HMB5nHuiZKuuCh1hS6CdVsv6C1NjYpVig=,tag:mAI1grIFdQwNxo1Aeo8uWQ==,type:str]
sops:
    age:
        - recipient: age1lmp8mkghh70kvwg2gx0svtc9n2e69js22ylxkt4fqgqfwqdu9y3qtznu3z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUlByOHJxR3I5ZXE3dVpJ
            Y1NNMlYzOXJsWVhtTVhxRXIvQzMvUDVPRmkwCmVlMzFsaDJsMjc2VjFRU1d5WjJP
            aWlCMTl4TkkzeWlsZ3pLYnIwNmZLcUEKLS0tIG11RmN5aS81dEFiSllCdVZVeWlN
            RjB2L3plSit5WGpPenhpS0RBT2lPRTAK4/wVBh3kTt6AclOr/aI4YdD8YexiQC/R
            k8D8KQ5up7YkMFCqdPveAxZXYnD3LMA9m+PVQnNhlb6BpH/8WmvtOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T21:40:49Z"
    mac: ENC[AES256_GCM,data:k4b9J3eu9Df+yBBCv/VEWRyCTJ4fZufE5FlaUgrJGyuGW/gPxma0JnMoCKljnPYHyShqusLIqNzwg7eTllF9U5k4LeKx2iuEZNVdKdI/Jkb4FM/uIeeXI18YdY9HpC/iwLxU4cdeSnqiXsgRsxYID+ZKMU3RGXtrgDESYiXHcX4=,iv:uHrpODXNRcl6iYe9quv5UGBahPMyGasHXOnG34bSKqc=,tag:hu88XMrTK1JUNsAWQjyGSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
