{{- if .Values.platformSecrets.enabled }}

{{- $root := . }}
{{- $secretDefaults := .Values.platformSecrets.secretDefaults | default dict }}

{{- range .Values.platformSecrets.secrets }}
{{- $secret := . }}

{{- if not $secret.name }}
{{- fail "platformSecrets.secrets[].name needs to be provided" }}
{{- end }}

{{- $storeRef := mergeOverwrite (deepCopy ($secretDefaults.storeRef | default dict)) ($secret.storeRef | default dict) }}
{{- $refresh := mergeOverwrite (deepCopy ($secretDefaults.refresh | default dict)) ($secret.refresh | default dict) }}
{{- $target := mergeOverwrite (deepCopy ($secretDefaults.target | default dict)) ($secret.target | default dict) }}
{{- $source := mergeOverwrite (deepCopy ($secretDefaults.source | default dict)) ($secret.source | default dict ) }}
{{- $namespaceSelectors := default $secretDefaults.namespaceSelectors $secret.namespaceSelectors }}

apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ $secret.name | quote }}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  externalSecretName: {{ $secret.name | quote }}

  {{- with $namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  refreshTime: {{ $refresh.clusterExternalSecret | quote }}

  externalSecretSpec:
    refreshInterval: {{ $refresh.externalSecret | quote }}
    secretStoreRef:
      name: {{ $storeRef.name | quote }}
      kind: {{ $storeRef.kind | quote }}

    target:
      {{- if $target }}
      name: {{ $target.secretName | quote }}
      {{- else }}
      name: {{ $secret.name | quote }}
      {{- end }}
      creationPolicy: {{ $target.creationPolicy | quote }}

    data:
      {{- range $secret.data }}
      - secretKey: {{ .secretKey | quote }}
        remoteRef:
          {{- if $source }}
          key: {{ $source.secretName | quote }}
          {{- else }}
          key: {{ $secret.name | quote }}
          {{- end }}
          property: {{ default .secretKey .property | quote }}
      {{- end }}
---
{{- end }}
{{- end }}
