{{- if .Values.platformSecrets.enabled }}

{{- $root := . }}
{{- range .Values.platformSecrets.stores }}

{{- if not .name }}
{{- fail (printf "Name needs to be provided" .name) }}
{{- end }}

{{- if not .serviceAccount.name }}
{{- fail (printf "Name needs to be provided" .name) }}
{{- end }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name | quote }} 
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ default (include "common.names.namespace" $root) .namespace | quote }} 
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ default (include "common.names.namespace" $root) .namespace | quote }} 
      auth:
        {{- with .serviceAccount }}
        serviceAccount:
          name: {{ .name | quote }} 
          namespace: {{ default (include "common.names.namespace" $root) .namespace | quote }} 
        {{- end }}
---
{{- end }}
{{- end }}
