# ===========================================================
# Purpose:  
# Notes:
# ===========================================================
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-tls-certificate
  namespace: envoy-gateway-system
spec:
  secretName: podinfo-tls-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - podinfo.anykey.pl
