# ===============================
# 
# ===============================
applications:

  # ------------------
  # PgAdmin4 
  # ------------------

    - name: pgadmin 
      enabled: false

  # ------------------
  # PhpLdapAdmin 
  # ------------------

    - name: phpldapadmin 
      enabled: false
