
{{- if and .Values.openldap.tls.enabled .Values.openldap.tls.certificate.enabled }}
{{- $root := . -}}
{{- with .Values.openldap.tls.certificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:  
  name: {{ default (printf "%s-tls" (include "common.names.fullname" $root )) .name }}
  namespace: {{ default (include "common.names.namespace" $root ) .namespace }}
spec:
  duration: {{ .duration | quote }}
  renewBefore: {{ .renewBefore | quote }}
  subject:
    organizations:
      {{- toYaml .subject.organizations | nindent 6 }}
  secretName: {{ default (printf "%s-tls" (include "common.names.fullname" $root )) .secretName }}
  privateKey:
    algorithm: {{ .keyAlgorithm }}
    size: {{ .keySize }}
  issuerRef:
    name: {{ required "certificate.existingIssuer is required when certificate.enabled=true" .existingIssuer }}
    kind: {{ default "Issuer" .existingIssuerKind }}
    group: cert-manager.io
  commonName: {{ first .dnsNames | default (printf "%s-tls" (include "common.names.fullname" $root)) | quote }}
  {{- with .dnsNames }}
  dnsNames:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
