apiVersion: v1
kind: Secret
metadata:
    name: shared-s3-credentials
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/SYOIpHS,iv:F0crWo/0yNOPsS9gd6G4Fa72j4n8G7jTPamzv7qsljU=,tag:AebgbrMtI58Rqx2MC2ZaAQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ovNFHxuHKpQH,iv:XvKZDKXZotXki8EqAXiuHX6uavFEiWc6BDz+Om6UnJ0=,tag:ekUVZMvodI6bqDYRZa8dHw==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT0NvWEFXTXlYcDBXSmRR
            R2lEQmdXQVM5SlMyWDhYbEZ5T2gwM005NXhJCm5xR0l0M2tkdkZYU3krN1J2bjBj
            bE5IU21EV0VSSEIwUE1JVTFreVdndGMKLS0tIHZJODhkam1CTzE5OXFlWVVoUmYr
            TnBkR2FkelB5cWFxRE1BSE9GNTUvWHMKLFUwUHZHTVtiyu6jBE98qx6Ct74BQHIh
            HHaXAr/zSPz3qdZB/shBHAriJHlIaBVVwH4HeMLHjkM24SRazSoBrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:40:31Z"
    mac: ENC[AES256_GCM,data:DmwMFHpidEAIycEiDouvmJLIyOGSQ9SDcERFGbFHOynBZisMjSQHH0i0f0xQVJrZjvGk+1pb83IDLvonuxAQpogwuuXqq5KXBsGVAfDdVoUbExaousf/g2/NIli+aih61X3bTDKV0YZaWEat4b7Go28F4IpWJX7FJqAyHN4KQeM=,iv:9FtuQmzNOg5vxsZj+RmksUJQ5b+B9ZWsa/jowes7drs=,tag:8ZwQs4EV/FlOzD/oEOiF0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
