apiVersion: v1
kind: Secret
metadata:
    name: shared-s3-credentials
    namespace: external-secrets
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OUzsrGkA,iv:8wVFxYI5Bsy2WkxaTbzhosu9rVvZECoB3jF0SZHQzes=,tag:BypO/FRc4IszDBrQyKhGMw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+kfW0dEM6sKd,iv:pZKqOeGCcg7ycz95u/3tgXb08xhC0/CCvFkY4kQTSs0=,tag:uIsDD48cB0Nl6I2ZvFgLaA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmZPZURXWE0yOWs5cFdt
            N0lXUUx4dm1TdURObFdBbXorR2MyN3hJWG5FCk5iNThEL3U2UWQ1QXBqV0lVVTJz
            M1d4ZGdZbWxyZjZwQkoxbUE4OVhYY3cKLS0tIEx4SUM4U1h3V2VmVERpUDIzTUk0
            N1NzSHh3SkJ3K1hBN011dnV4ZGR1cUEKv/J+DDUEOr6/B/+6hysLlClGApUUr6ML
            kfmkntnSniZLU6/+T2ycdvpZ28ODukIjKJyi3S7mIGcHhc95BtWJHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T21:47:39Z"
    mac: ENC[AES256_GCM,data:OcQbqt/8UV88OnwA1DMp+bLx2Sj/NyS2AUqgyiNpiafWR/cmEgpdv9OJH30ycsnE2n+yMW7b4qDp7s4U/sBf8brmYywb9q0IcMonA6G0FaWepZnZdYf2F0aDAjTq2MD/ZZTjO3hJyfIhHc+iciEBH1uDUSBJ5icrnzwEun2GLsQ=,iv:LkJSbFeRd/LWhtNXZjdb6jNxtSMH/6F4riprvxh6q60=,tag:FvCfAb2ale+8x0mcXTHzBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
