master:
  enabled: true
  replicas: 1

volume:
  enabled: true
  replicas: 1
  dataDirs:
    - name: data
      type: persistentVolumeClaim
      storageClass: "storage-local-retain"
      size: "50Gi"
      maxVolumes: 0

filer:
  enabled: true
  replicas: 1

s3:
  enabled: true
  replicas: 1
  bindAddress: 0.0.0.0
  port: 8333
  httpsPort: 0
  existingConfigSecret: seaweedfs-s3-secret
  createBuckets:
    - name: nextcloud
      anonymousRead: false
  enableAuth: true
  service:
    type: ClusterIP

cosi:
  enabled: true
  image: "ghcr.io/seaweedfs/seaweedfs-cosi-driver:v0.3.0"

  driverName: "seaweedfs.objectstorage.k8s.io"
  bucketClassName: "seaweedfs"

  endpoint: "http://seaweed-filer.seaweedfs-operator.svc.cluster.local:8333"
  region: "us-east-1"

  enableAuth: true
  existingConfigSecret: seaweed-cosi-s3-config

  extraEnvironmentVars:
    SEAWEEDFS_FILER: seaweed-filer.seaweedfs-operator.svc.cluster.local:18888

  #cosi:
  #  enabled: true
  #  image: "ghcr.io/seaweedfs/seaweedfs-cosi-driver:v0.3.0"
