apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: shared-s3-credentials
  namespace: external-secrets
spec:
  externalSecretName: shared-s3-credentials

  namespaceSelectors:
    - matchLabels:
        shared-s3-creds: "true"

  refreshTime: 1m

  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-shared-secrets
      kind: ClusterSecretStore

    target:
      name: s3-credentials
      creationPolicy: Owner

    data:
      - secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          key: shared-s3-credentials
          property: AWS_ACCESS_KEY_ID
      - secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          key: shared-s3-credentials
          property: AWS_SECRET_ACCESS_KEY
