# ===========================================================
# Purpose:
#
# ===========================================================
config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info

service:
  # If set to PreferClose, the Envoy fleet will prioritize connecting to the Envoy Gateway pods that are topologically closest to them.
  trafficDistribution: ""
  annotations: {}
  # -- Service type. Can be set to LoadBalancer with specific IP, e.g.:
  # type: LoadBalancer
  # loadBalancerIP: 10.236.90.20
  type: "ClusterIP"

topologyInjector:
  enabled: false
