# ===============================
# 
# ===============================
applications:

  # ------------------
  # Argo-CD - Gateway-API
  # ------------------
  
    - name: argocd-extras
      namespace: argocd

      enabled: false
      priority: 0

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-charts/wrappers/app-platform
          valueFiles: 
            - $values/platform-products/platform-extras/applications/argocd-extras/helm/values.yml

        - type: kustomize 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-extras/applications/argocd-extras/kustomize
