# ===============================
# 
# ===============================
applications:

  # ------------------
  # Cosi 
  # ------------------

    - name: cosi 
      enabled: true 

  # ------------------
  # CloudNative-PG
  # ------------------

    - name: cloudnative-pg 
      enabled: true

  # ------------------
  # Local Path Provisioner 
  # ------------------

    - name: local-path-provisioner 
      enabled: true

  # ------------------
  # Rook Ceph 
  # ------------------

    - name: rook-ceph 
      enabled: false

  # ------------------
  # SeaWeedFS 
  # ------------------

    - name: seaweedfs 
      enabled: true

  # ------------------
  # SeaWeedFS-Operator
  # ------------------

    - name: seaweedfs-operator
      enabled: true
