# ===============================
# 
# ===============================
applications:

  # ------------------
  # Local Path Provisoner 
  # ------------------
  
    - name: local-path-provisioner
      namespace: kube-system

      enabled: true
      priority: -10

      syncPolicy:
        automated: false

      sources:

        - type: manifests
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/workload-storage/applications/local-path-provisoner/manifests

  # ------------------
  # CloudNativePG (postgresql-operator)
  # ------------------

    - name: cloudnative-pg
      namespace: postgresql-operator

      enabled: true
      priority: -10

      syncPolicy:
        automated: false
        syncOptions:
          - ServerSideApply=true

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://cloudnative-pg.io/charts/
          targetRevision: 0.28.0
          chart: cloudnative-pg
          valueFiles: 
            - $values/platform-products/platform-storage/applications/cloudnative-pg/helm/values.yml

  # ------------------
  # PGAdmin 
  # ------------------

    - name: pgadmin 
      namespace: pgadmin 

      enabled: true
      priority: -5

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://helm.runix.net
          targetRevision: 1.62.0 
          chart: pgadmin4
          valueFiles: 
            - $values/platform-products/platform-storage/applications/cloudnative-pg/helm/values.yml

        - type: helm 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: head
          path: platform-charts/application/app-platform
          valueFiles: 
            - $values/platform-products/workload-tests/applications/podinfo/helm/values.yml

        - type: helm 
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: head
          path: platform-charts/application/app-security
          valueFiles: 
            - $values/platform-products/workload-tests/applications/podinfo/helm/values.yml
