# ===============================
# 
# ===============================
applications:

  # ------------------
  # Local Path Provisoner 
  # ------------------
  
    - name: local-path-provisioner
      namespace: kube-system

      enabled: true
      priority: 0 

      syncPolicy:
        automated: false

      sources:

        - type: manifests
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-storage/applications/local-path-provisioner/manifests

  # ------------------
  # CloudNativePG (postgresql-operator)
  # ------------------

    - name: cloudnative-pg
      namespace: postgresql-operator

      enabled: true
      priority: 0

      syncPolicy:
        automated: false
        syncOptions:
          - ServerSideApply=true

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://cloudnative-pg.io/charts/
          targetRevision: 0.28.0
          chart: cloudnative-pg
          valueFiles: 
            - $values/platform-products/platform-storage/applications/cloudnative-pg/helm/values.yml

        - type: helm
          repoURL: https://cloudnative-pg.io/charts/
          targetRevision: 0.6.0
          chart: plugin-barman-cloud 

  # ------------------
  # COSI 
  # ------------------

    - name: cosi
      namespace: cosi 

      enabled: true
      priority: 0

      syncPolicy:
        automated: false

      sources:

        # Install COSI CRDs & Controller
        - type: kustomize 
          repoURL: https://github.com/kubernetes-sigs/container-object-storage-interface
          targetRevision: HEAD 
          path: . 

  # ------------------
  # SeaweedFS (S3)
  # ------------------

    - name: seaweedfs 
      namespace: seaweedfs 

      enabled: true
      priority: 0

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://seaweedfs.github.io/seaweedfs/helm 
          targetRevision: 4.23.0
          chart: seaweedfs
          valueFiles: 
            - $values/platform-products/platform-storage/applications/seaweedfs/helm/values.yml

  # ------------------
  # SeaweedFS Operator (S3) 
  # ------------------

    - name: seaweedfs-operator
      namespace: seaweedfs 

      enabled: false
      priority: 0

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://seaweedfs.github.io/seaweedfs-operator
          targetRevision: 0.1.22 
          chart: seaweedfs-operator
          valueFiles: 
            - $values/platform-products/platform-storage/applications/seaweedfs-operator/helm/values.yml

        - type: manifests
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          path: platform-products/platform-storage/applications/seaweedfs-operator/manifests

  # ------------------
  # RookCeph (3s-only) / DISABLED
  # TIP:
  #   - we need here 3 nodes to properly configure MON monitor
  # ------------------

    - name: rook-ceph 
      namespace: rook-ceph 

      enabled: false
      priority: 0

      syncPolicy:
        automated: false

      sources:

        - type: values
          repoURL: https://github.com/wsadza/homelab.git
          targetRevision: HEAD
          ref: values

        - type: helm
          repoURL: https://charts.rook.io/release
          targetRevision: v1.19.5
          chart: rook-ceph
          valueFiles: 
            - $values/platform-products/platform-storage/applications/rook-ceph/helm/values.yml
