# ===============================================
# Author: Igor Sadza 
# Purpose: Manage keycloak instacne 
# ===============================================

# -----------------------------------------------
# @section common parameters
# -----------------------------------------------
#
# @param nameOverride      : String to partially override common.names.name
# @param fullnameOverride  : String to fully override common.names.fullname
# @param namespaceOverride : String to fully override common.names.namespace
# @param commonLabels      : Labels to add to all deployed objects
# @param commonAnnotations : Annotations to add to all deployed objects
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
commonLabels: {}
commonAnnotations: {}

# ===============================================
# : platformAuth (wrapper)
# ===============================================

platformAuth:

  # ===============================================
  # @section Keycloak parameters
  # =============================================== 
  #
  keycloak:
    enabled: true 

    # -----------------------------------------------
    # @subsection endpoint parameters
    # -----------------------------------------------
    #
    endpoint:
      url: http://keycloak-service.keycloak.svc.cluster.local:8080 
      secret: keycloak-admin-secret

    # -----------------------------------------------
    # @subsection relam parameters
    # -----------------------------------------------
    #
    realm:
      name: platform

    # -----------------------------------------------
    # @subsection relamComponent parameters
    # -----------------------------------------------
    #
    realmComponents:
      - name: openldap
        enabled: true
        providerId: ldap
        providerType: org.keycloak.storage.UserStorageProvider
        config:
          enabled:
            - "true"
          vendor:
            - "other"
          connectionUrl:
            - "ldaps://openldap.anykey.pl"
          bindDn:
            - "cn=admin,dc=anykey,dc=pl"
          bindCredential:
            - "$openldap-admin-secret:LDAP_ADMIN_PASSWORD"
          usersDn:
            - "ou=users,dc=anykey,dc=pl"
          usernameLDAPAttribute:
            - "uid"
          rdnLDAPAttribute:
            - "uid"
          uuidLDAPAttribute:
            - "entryUUID"
          userObjectClasses:
            - "inetOrgPerson, organizationalPerson"
          editMode:
            - "WRITABLE"
          importEnabled:
            - "true"
          syncRegistrations:
            - "true"

    # -----------------------------------------------
    # @subsection groups parameters
    # -----------------------------------------------
    #
    groups:
      - name: platform-admins
        enabled: true
        groupName: PlatformAdmins
        namespace: keycloak
        labels: {}
        annotations: {}

    # -----------------------------------------------
    # @subsection clientScopes parameters
    # -----------------------------------------------
    #
    clientScopes:
      # Groups assigned to the user
      - name: groups
        enabled: true
        protocol: openid-connect
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              claim.name: groups
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"

    # -----------------------------------------------
    # @subsection userDefaults parameters
    # -----------------------------------------------
    #
    userDefaults: 
      enabled: true
      emailVerified: false
      passwordSecret:
        mode: create # existing | create | none
        name: ""
        key: password
        value: "changeme"
      requiredUserActions: []
      roles: []
      groups: []
      reconciliationStrategy: full
      keepResource: true

    # -----------------------------------------------
    # @subsection users reference parameters
    # -----------------------------------------------
    #
    users:
    # 1: Consuming defaults
    - username: john.doe
    # 2: Overriding defaults
    - username: jan.kowalski 
      enabled: true
      firstName: john
      lastName: doe 
      email: jan.kowalski@example.com
      emailVerified: true
      passwordSecret:
        mode: existing
        name: jan-kowalski-password
        key: password
      requiredUserActions:
      - UPDATE_PASSWORD
      roles:
      - offline_access
      groups:
      - PlatformAdmins
      reconciliationStrategy: full
      keepResource: true       
