mode: root
repoURL: https://github.com/wsadza/homelab.git
targetRevision: HEAD

# --------------------------
# -- TOP-Generator --------
# ------------------------

root:
  name: test
  file: environments/dta.yml 
  listKey: products

  # -- Child (node) ------------
  childMode: node
  childChartPath: platform-charts/foundation/appset-factory-v2
  childFileTemplate: "platform-products/{{ product }}/applications.yml"
  childNameTemplate: "{{ product }}"

# --------------------------
# -- MID-Generator --------
# ------------------------

node:
  name: ""
  file: ""
  product: ""
  listKey: applications

  # -- Child (leaf) ------------
  childMode: leaf
  childChartPath: platform-charts/foundation/appset-factory-v2
  childFileTemplate: "platform-products/{{ product }}/applications/{{ application }}/components.yml"
  childNameTemplate: "{{ application }}"

# --------------------------
# -- Sources --------------
# ------------------------

leaf:
  name: ""
  file: ""
  product: ""
  listKey: components
