{{- if .Values.appStorage.blob.enabled }}
{{- $fullname := include "common.names.fullname" . }}
{{- $baseName := default $fullname .Values.appStorage.blob.nameOverride }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret" $baseName | quote }}
  namespace: {{ default (include "common.names.namespace" .) .Values.appStorage.blob.namespace  | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-store" $baseName | quote }}

  target:
    name: nextcloud-s3-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        S3_BUCKET: {{ `{{ $b := .bucketInfo | fromJson }}{{ index $b "spec" "bucketName" }}` | quote }}
        S3_ENDPOINT: {{ `{{ $b := .bucketInfo | fromJson }}{{ index $b "spec" "secretS3" "endpoint" }}` | quote }}
        S3_REGION: {{ `{{ $b := .bucketInfo | fromJson }}{{ index $b "spec" "secretS3" "region" }}` | quote }}
        S3_ACCESS_KEY: {{ `{{ $b := .bucketInfo | fromJson }}{{ index $b "spec" "secretS3" "accessKeyID" }}` | quote }}
        S3_SECRET_KEY: {{ `{{ $b := .bucketInfo | fromJson }}{{ index $b "spec" "secretS3" "accessSecretKey" }}` | quote }}

  data:
    - secretKey: bucketInfo
      remoteRef:
        key: {{ default (printf "%s-object-store-secret" (include "common.names.fullname" .)) .Values.appStorage.blob.secretName | quote }}
        property: BucketInfo
{{- end }}
