mode: root

repoURL: https://github.com/wsadza/homelab.git
targetRevision: HEAD

root:
  listKey: domains
  name: domains
  file: environments/dev.yml 

  childChartPath: platform-charts/foundation/appset-factory
  childMode: leaf
  childFileTemplate: "platform-domains/{{ item }}/product.yml"
  childNameTemplate: "{{ item }}"

leaf:
  listKey: domains 
  name: ""
  file: ""
