apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: psql-backup
  namespace: nextcloud
spec:
  cluster:
    name: nextcloud-postgresql
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
