apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgresql 
  namespace: nextcloud 
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: nextcloud 
      owner: nextcloud 
      secret:
        name: nextcloud-database-secret

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: seaweedfs-store
        serverName: nextcloud

  storage:
    size: 20Gi
    storageClass: storage-local-retain
  monitoring:
    enablePodMonitor: true
