apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: seaweedfs-store
  namespace: nextcloud
spec:
  configuration:
    destinationPath: s3://app-bucket/nextcloud-postgresql
    endpointURL: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
    s3Credentials:
      accessKeyId:
        name: seaweedfs-s3-secret
        key: accessKey 
      secretAccessKey:
        name: seaweedfs-s3-secret
        key: secretKey 
    wal:
      compression: gzip
    data:
      compression: gzip
