provider: ovh

sources:
  - service
  - ingress
  - gateway-httproute

policy: sync

registry: txt
txtOwnerId: homelab-dev
txtPrefix: external-dns-

interval: 1m

domainFilters:
  - anykey.pl 

  #extraArgs:
  #  - --source=service # ingress is also possible
  #  - --domain-filter=anykey.pl # (optional) limit to only example.com domains; change to match the zone created above.

env:
  - name: OVH_APPLICATION_KEY
    valueFrom:
      secretKeyRef:
        name: external-dns-ovh
        key: applicationKey
  - name: OVH_APPLICATION_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-ovh
        key: applicationSecret
  - name: OVH_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        name: external-dns-ovh
        key: consumerKey

serviceAccount:
  create: true
  name: external-dns

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
