apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClaim
metadata:
  name: app-bucket-v2
  namespace: seaweedfs 
spec:
  #existingBucketName: app-bucket-v2
  bucketClassName: seaweedfs
  bucketName: nextcloud-app-bucket
  protocols:
    - s3
