postgresql:
  enabled: false

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8080

extraEnv: |
  - name: KC_DB
    value: postgres

  - name: KC_DB_URL
    value: jdbc:postgresql://keycloak-postgresql-rw.keycloak.svc.cluster.local:5432/keycloak

  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-db-secret
        key: username

  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-db-secret
        key: password

  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: username

  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: password

  - name: KC_HOSTNAME
    value: keycloak.anykey.pl

  - name: KC_PROXY_HEADERS
    value: xforwarded

  - name: KC_HTTP_ENABLED
    value: "true"
