# For OICD configurations
# We want here to make this secret available for application 
apiVersion: v1
kind: Secret
metadata:
    name: podinfo-keycloak-client-secret
    namespace: nextcloud
stringData:
    client-secret: 
---
# For Keycloak configurations
# We want here to make this secret available for keycloak operators
apiVersion: v1
kind: Secret
metadata:
    name: podinfo-keycloak-client-secret
    namespace: keycloak
stringData:
    client-secret:  
