{{- if .Values.appStorage.blob.enabled }}
{{- $fullname := include "common.names.fullname" . }}
{{- $baseName := default $fullname .Values.appStorage.blob.name }}
apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  name: {{ printf "%s-bucket" $baseName | quote }}
  namespace: {{ default (include "common.names.namespace" .) .Values.appStorage.blob.namespace  | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  bucketClaim:
    name: {{ default (printf "%s-bucket-claim" (include "common.names.fullname" .)) .Values.appStorage.blob.name | quote }}
    namespace: {{ default (include "common.names.namespace" .) .Values.appStorage.blob.namespace | quote }}
  bucketClassName: {{ .Values.appStorage.blob.bucketClassName | quote }}
  deletionPolicy: {{ .Values.appStorage.blob.deletionPolicy | quote }}
  driverName: {{ .Values.appStorage.blob.driverName | quote }}
  existingBucketID: {{ default (printf "%s-seaweedfs-bucket" (include "common.names.fullname" .)) .Values.appStorage.blob.name | quote }}
  protocols:
    - S3
{{- end }}
