# --
# 
# 
# --
applications:

    - name: podinfo
      enabled: false
      chartName: podinfo
      #chartPath: ./deploy/chart/local-path-provisioner 
      #chartValues: 
      targetRevision: 6.11.2
      repoURL: https://stefanprodan.github.io/podinfo
      #manifests: 
      #namespace: 
      #priority:
