# ===============================
# 
# ===============================
applications:

  # ------------------
  # Local Path Provisoner 
  # ------------------

    - name: local-path-provisioner
      chartName: local-path-storage
      enabled: true 
      chartPath: ./deploy/chart/local-path-provisioner 
      targetRevision: v0.0.35
      repoURL: https://github.com/rancher/local-path-provisioner
      manifests: true
      chartValues: true
      namespace: local-path-provisioner
      priority: 0
