# ===============================
# 
# ===============================
applications:

  # ------------------
  # Local Path Provisoner 
  # ------------------

    - name: local-path-provisioner
      enabled: true 
      chartName: local-path-provisioner
      chartPath: ./deploy/chart/local-path-provisioner 
      chartValues: true
      targetRevision: v0.0.35
      repoURL: https://github.com/rancher/local-path-provisioner
      #manifests: 
      #namespace: 
      #priority:
