apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-client
    namespace: seaweedfs
stringData:
  # openssl rand -hex 32
  clientSecret: e83c69ea7e9444eda037c1460de5feb49bdf85294ce1398cee22654b1fbb61c4
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-client
    namespace: keycloak
stringData:
  # openssl rand -hex 32
  clientSecret: e83c69ea7e9444eda037c1460de5feb49bdf85294ce1398cee22654b1fbb61c4
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-sts-signing-key
stringData:
  # openssl rand -hex 64
  signingKey: 187598f3f04131605afc64a00cda3e1ecb38dd58476aff0a5d7f72dfff61f0c0875b6e865137c3087a4b3cd44b39e7b7e658f42320fb9b8b5b561b424d7ddc71
---
