apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: keycloak-system
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:6OYjTKwjum/x,iv:3FPl1pD6NXhze3xO+HZ3Z4dKFugC3H3XsXnJzft7FLk=,tag:a4IoAqX2HGgmPT269qYxxg==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:L0i8xJdzvZjK,iv:AtcYBYOzN0B5JpmIJ/2e9RkzN6iS9lKNmWvFlp0yFBE=,tag:injFOHr503eNYzpW84L9WA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQzB3bTZVZXdCdUhtKzZ5
            RHNsR1pydGEzUnl6UDZIR0p6M2ZnU1U5ZVZRCldyYzREYzh2NmRvelZ2YkU5SWNY
            dThibndzYldsakJBQzVZeXZWb2VPS2cKLS0tIC9lc1ovMVlEZjdqckNSbWRXSEho
            VkM2N1ROUEJSdERwRnh1SkllNDZ2dmsKSfPv4uzB5WgSzpOwa4xJBlHp1HIYC78K
            8msaLiTsM4ZLjiSjvoVWQtxPAV87YLGad4ksYMobXElHkgwKp/awYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:01:01Z"
    mac: ENC[AES256_GCM,data:UBpBtoVdcJdb07ApNe3imZszLqZ7HHQvBJs5h2XWpx6Ni7xMZkYxWY9anyVpv23BnbAEuix59rZ1l2nB20O0RA3k6i3Dsm9Oe83syHz6cDDHYacMi+C44ZQSc1CaJ787F/jNv1SXgtJcwXV0VVu81ZHpKSZKZm/Q5yecODGKE2c=,iv:+FtibT+5NOoC2lpfrey44bvb5vIZFEdXP3HlcQhezfU=,tag:29zvWkuFx62StxoETaVaYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:n1x0fb7w,iv:xKHAtGm+Ml0+YJSZreY75UR0C9/yq1BHHrb+fb5jVnA=,tag:3JzAe5jnEhEoNoDOo6eY9Q==,type:str]
    password: ENC[AES256_GCM,data:P8so/03MaJcX,iv:2kB/iQ8KTz6HUqZzc0aavirwK7GbnSg+TX4SQrtKClc=,tag:fvk+Hgz6pLbTj0yR69mizA==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQzB3bTZVZXdCdUhtKzZ5
            RHNsR1pydGEzUnl6UDZIR0p6M2ZnU1U5ZVZRCldyYzREYzh2NmRvelZ2YkU5SWNY
            dThibndzYldsakJBQzVZeXZWb2VPS2cKLS0tIC9lc1ovMVlEZjdqckNSbWRXSEho
            VkM2N1ROUEJSdERwRnh1SkllNDZ2dmsKSfPv4uzB5WgSzpOwa4xJBlHp1HIYC78K
            8msaLiTsM4ZLjiSjvoVWQtxPAV87YLGad4ksYMobXElHkgwKp/awYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:01:01Z"
    mac: ENC[AES256_GCM,data:UBpBtoVdcJdb07ApNe3imZszLqZ7HHQvBJs5h2XWpx6Ni7xMZkYxWY9anyVpv23BnbAEuix59rZ1l2nB20O0RA3k6i3Dsm9Oe83syHz6cDDHYacMi+C44ZQSc1CaJ787F/jNv1SXgtJcwXV0VVu81ZHpKSZKZm/Q5yecODGKE2c=,iv:+FtibT+5NOoC2lpfrey44bvb5vIZFEdXP3HlcQhezfU=,tag:29zvWkuFx62StxoETaVaYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
