apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:v0/3wnX5I29F,iv:71wOB/mAT7q+BbWzRiQrTBXu30AHujduUbMNBqYWmRs=,tag:OHlIDEu+ZW3MkcCCNwv86A==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:3kgzRUdVMUvk,iv:YVxVhuS8GA4U9yv6c4h+9cxMM4FVk4auBh6ocHYPBTs=,tag:pH4/PPJhPisPBvuFjZ1hyg==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzF5WDlub1BBaEhod0JC
            RnRxSVRzMURnOGJoN0dCZWthSk1OTTljQkdrCldvdGkwSWRQN1hzaHhSVHJoaEla
            UlIxQm5ZZGdzUTYwcVQycXhnNGVOOTgKLS0tIDVBcWQrd05xdXZXR1NsYUlIVk41
            YTh6TU4wUWowWlhCSmY4RkhPVXpMcDQKBDTTezP22dqe2nxCN+BCZN9T1TPqrkM8
            IRVVYEQ6MyjZIjrMXjbOY7dn3o3jpQPGlpqoQ/HV2JHavuaWWp+/XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:20:35Z"
    mac: ENC[AES256_GCM,data:OPwnS0n2eKCEy/YGfc+f1i4bQuiIyKgZxlHTCKcYL10SlrXBUE/EP2HO+cCMOO1+Jsw4P+XPtXfF9VFARhmlNmvGJydAKzjmCkIeGOxOQ9EnbTTKsIMWtN4gDtYVcTn8VeqoUBsGFZY2uzqdKhUSKX/0A6bIgMR/t5nhXOThFwM=,iv:u7jEYQygmm0iuieRzC0sdc44uDf2kFvW2bebpLCj4TE=,tag:UlfNJH3PdKV65C2vC+38Ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
