apiVersion: v1
kind: Secret
metadata:
    name: openldap-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:2N5UUDz/YOMn,iv:fNycXAI+QpsNptrQPhmmOTupiyaT1bf5O3B0cA1p22Q=,tag:TecwzHSE6jPr1lDsQno+lw==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:CTLOgfBzVUw9,iv:ql7XeFq4Jk8FUd2MsQD5hwpXMGSujoKcnV73EOEb94c=,tag:yFBDfAZ6WV5eEAn3LeJ3EQ==,type:str]
sops:
    age:
        - recipient: age13znhh2uaq04wtt88l0qluzuve4k5xup97kehshexmew07kkhn4gsgq8srx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVlEycHpUMXRja1FYcW1Y
            d0cyR29PT2ZEMVE2VnZsRTdIUnpvSittZlRJCkdNOTAza2x2QnJpSnpmY0lkWTJo
            MDFFSG5STDV5dEdIalNZWGpvdldjeUUKLS0tIFg4Zng3T2puc3pFanFlcXF3Yk83
            aTcwUzk1Q0dQZXpyUmpONW1zSVZiNjQKc7hdGE0IO9XxeYnZWoCDcBzKSPnTVvv9
            vfKQ/XNo3uuY8NSw/8RbtlPwduVFMS/uwiD/Si6103ErwCehYSK54A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T23:56:18Z"
    mac: ENC[AES256_GCM,data:gmkx2ZZXviVBuek6j5m5UMHGiJJgTpVNjT3hS/B8iP9s7EQaz9T0aDjL3Glo6T+g57f0tMO4ym5kIupTQaCtKMmOqeaV+a1lO7yX5gt9deMVMm2KTGr5x3o/1/WR9MLvoyE1A8nNM0Yczop+NZGuQEkQ1v4S+P2GVpquYxNGAKI=,iv:0/wnTdh7um2vp4QoYqaNRDMVIwNNTNucp5Dg4z3CiIM=,tag:3pV3KK1phYoD/jkYmIaVxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
