# ===========================================================
# Purpose:  
# Notes:
# ===========================================================
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-argocd
  namespace: envoy-gateway-system
spec:
  acme:
    email: argocd@anykey.pl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: gateway-argocd
                namespace: envoy-gateway-system
---
